### ISSUE TITLE
[Question] How's the notifications/reminder email works?

### ISSUE THREAD

**Issue by WinsenTjhang** [google/loaner#100]
### Expected Behaviour
Received email notification during log in and returning device

### Actual Behaviour
Did not receive notifications

### Reproduce
Config version 1: I put the SEND_EMAIL_AS constant equal to my admin email and put the authorized email sender using the same email. 

Config 2: Put the loaner role accounts

How's the app sending email notifications works? Does it require an account with G Suite license?

**Comment by helfrichmichael** [comment]
Please include errors from Google Cloud Logging or what steps you've taken to troubleshoot so far.

Additionally, please check your task queues in Google Cloud Platform and ensure they aren't paused/erroring.

As far as I can remember, the account doesn't have to exist, it just must be an authorized sender in GCP. We use a noreply@ address usually.

**Comment by WinsenTjhang** [comment]
Hi Michael,

I think the account needs to be exist

![image](https://user-images.githubusercontent.com/43067876/78730679-e2703280-7980-11ea-9939-dedadf6b45e2.png)

Here what I tried:
SEND_EMAIL_AS = 'winsen@geekycloud.com'

![image](https://user-images.githubusercontent.com/43067876/78733767-b60ce400-7989-11ea-8366-3a2758d21e8c.png)

that account is an active account with a license attached

I have flushed the Memcache and redeployed the web app

Logs

![image](https://user-images.githubusercontent.com/43067876/78735604-86140f80-798e-11ea-97a1-d9e09da97461.png)

![image](https://user-images.githubusercontent.com/43067876/78733897-17cd4e00-798a-11ea-8f14-e2b608b23e5a.png)

![image](https://user-images.githubusercontent.com/43067876/78733912-2ae01e00-798a-11ea-841d-6ff4699f50b4.png)

**Comment by helfrichmichael** [comment]
Did you update the serving version for each App Engine instance (action-system, chrome, default, and endpoints)? Additionally, if you debug the version running via the App Engine view and open the constants.py, is the email the email address you expect?

You're right regarding the email needing to exist. I confirmed it does exist on our end. Apologies for the confusion around that.

**Comment by WinsenTjhang** [comment]
It works now! Apparently I have been only updating my default system since my first deployment. Thanks a lot for the help!

No worries, also G Suite license is essential for the account.

**Comment by helfrichmichael** [comment]
That's great to hear and yeah, unfortunately it's not always obvious that you need to update each serving version. I'll close this out.
