### ISSUE TITLE
[QUESTION] Where in the code are stored the devices when enrolled in Grab and Go

### ISSUE THREAD

**Issue by StephaneConq** [google/loaner#101]
Hi,

I am currently working on a Grab and Go implementation for a client. They want to store some more details about the Chrome device, and display them in the device list interface.

My question is : when a device is enrolled in the frontend, the /device/enroll api call is sent to the backend, I see where the device is fetched from the Gsuite console, but where to we tell to store the device in Datastore ?

Is it this line ? https://github.com/google/loaner/blob/master/loaner/web_app/backend/models/device_model.py#L377

Is that a class method from Datastore classes ?

**Comment by helfrichmichael** [comment]
Correct, the class method is what pushes all of the data into datastore. This will store the entities in the `Device` kind on datastore.

Let me know if you have any further questions :).
