### ISSUE TITLE
Is there a simple way to update a Datastore entity

### ISSUE THREAD

**Issue by StephaneConq** [google/loaner#102]
Hi,

I have been asked to add a field in the Device kind in Datastore.
I basically want to add a 'column' or 'field' in the Device entity.
I there a simple way to do it, like just updating the device_model.py file with the field I want ?

Thanks in advance.

**Comment by helfrichmichael** [comment]
Yeah, you can modify the [Device class](https://github.com/google/loaner/blob/master/loaner/web_app/backend/models/device_model.py#L178) for example if you want to add additional fields. Do note that if you plan on doing anything with that field on the Frontend/Chrome App, you may need to modify the models/code to handle this new field on the Frontend/Chrome App.

**Comment by StephaneConq** [comment]
Sure, that's exacly what I was going to do.
When I'll update the model in the class, do I need to do a specific action somewhere to update the model in the database with the model in the code, like a migration or something like this?

**Comment by helfrichmichael** [comment]
Without context, I think you should be fine with just introducing a new field and providing a type (it should be visible in Datastore once you promote the latest App Engine service versions). You may need to bootstrap once again after modifying, but I don't think this will be the case.

Depending on what the field is doing, there might be additional steps that need to be taken to get the entity to match up properly in datastore. The only other thing you might need to do is reindexing the device entities via the configuration page in the Web App.
