### ISSUE TITLE
02368551_Chromebook extension needed until Jan 15th

### ISSUE THREAD

**Issue by KusumaGuntamadugu** [google/loaner#116]
Hi Team,

I haven't got my Mac back from IT after giving it for an upgrade. Hopefully, I will be getting it back on 15th Jan.

Can you please help in extending the Chromebook loan till 15th Jan as I am not able to do it in the website

**Comment by helfrichmichael** [comment]
Hi @KusumaGuntamadugu please contact your organization to extend your loaner. This is the Open-source Software repository that is used to deploy Grab n Go for companies.
