### ISSUE TITLE
02346073_Chrome book extension needed until 18th Feb

### ISSUE THREAD

**Issue by nmatsushita-wowcorp** [google/loaner#117]
Hello

Will you extend my Chrome book due date till 18th Feb as I cannot extend it on the web page any longer?
I am relatively new to Woolworths and have not received the corporate laptop.
It has been ordered and is coming, and I need to hold the Chrome book until I receive my laptop.

Kindly

**Comment by helfrichmichael** [comment]
Hi @KusumaGuntamadugu please contact your organization to extend your loaner. This is the Open-source Software repository that is used to deploy Grab n Go for companies.

**Comment by helfrichmichael** [comment]
Hi @nmatsushita please contact your organization to extend your loaner. This is the Open-source Software repository that is used to deploy Grab n Go for companies.
