### ISSUE TITLE
Gsuite OU groups require ENV OU

### ISSUE THREAD

**Issue by iamgeef** [google/loaner#12]
The Docs specify creating OU groups as below:
>Grab n Go
>>Default
>>Guest Enabled

When attempting to Bootstrap, it is actually looking for:
>Grab n Go
>> PROD
>>> Default
>>> Guest Enabled

![logs_viewer_-_chromebook-loaners_-_google_cloud_platform](https://user-images.githubusercontent.com/10751405/46184020-f9a77c00-c316-11e8-8f88-36cd15346772.png)

**Comment by helfrichmichael** [comment]
Thanks for catching this. We'll work on adjusting this.

**Comment by helfrichmichael** [comment]
I've fixed this upstream for the bootstrap helper and also our gSuite OU diagram and it should be included in our next Github push.
