### ISSUE TITLE
Forbidden - After of Build and Deploy the GnG app.

### ISSUE THREAD

**Issue by JoshSanchezG** [google/loaner#13]
### Expected Behaviour
To open the GnG Web app in the default web browser in order to Bootstrap it (the first time).

### Actual Behaviour
I'm getting this message: "Forbidden" when I build and deploy the app. The URL is: 
https://[project id].appspot.com/, even if I build and deploy it locally I get the same error.

### Steps to Reproduce
I'm thinking that the problem is related with: my google account in Google Admin console is not a full admin so the app never is start the "Bootstrapping" process. But I need to confirm this.

Thanks in advance.

**Comment by Sasho11** [comment]
Please provide any error that may be popping up in [GCP logging ](https://cloud.google.com/logging/docs/view/overview) or in the [developer console](https://developers.google.com/web/tools/chrome-devtools/console/get-started) within Google Chrome while accessing the application.

**Comment by JoshSanchezG** [comment]
Hi Sasho11,

It's just a message in the web page that says: "Forbidden", you can see the image that I have added:

![screenshot 2018-11-15 at 15 24 23](https://user-images.githubusercontent.com/43448488/48583112-ef076d00-e8eb-11e8-85cf-b826b205d551.png)

Regards!

**Comment by iamgeef** [comment]
I usually get this message if I try to connect with an email that isn't in the specified domain

Is your gsuite account in the same domain as set in loaner/web_app/constants.py APP_DOMAIN value?
Or if you are using Chrome are you signed in to the browser with a different account?

**Comment by JoshSanchezG** [comment]
Hi all,

  Thanks, I corroborate the APP_DOMAIN value and I detected a character that is not valid (Thanks Iamgeef).

Now, I'm getting this error:

Internal Server Error
The server has either erred or is incapable of performing the requested operation.
ValueError: Service account info was not in the expected format, missing fields token_uri, client_email.

My account has configured a 2FA. What can I do?

Thanks in advance guys for your help :)

**Comment by JoshSanchezG** [comment]
Hello,

  I have fixed the error, the domain has a special character. After that I was able to continue, but now I'm getting this error: "line 379, in _users_in_group
    raise DirectoryRPCError(err.resp.reason)" and I have seen that there is another issue reporting this (Bootstrap first access error #20), I will close this.

Thanks and regards!
