### ISSUE TITLE
Issue getting Bazel version when deploying from CentOS 7

### ISSUE THREAD

**Issue by ampkeegan** [google/loaner#14]
Deploying GNG from a GCP hosted Centos 7 Linux VM.

The deployment.sh script is failing due to an incorrect version number for bazel.

My current bazel version is:

-bash-4.2$ bazel version
Build label: 0.17.2- (@non-git)

The hyphen on the end is breaking the case on line 141 of deploy.sh, the BAZEL_VERSION variable is being set to '172-' instead of just 172.

The fix is change line 144 from:

`| sed 's/\(^0*\|\.\)//g');;`

to:

`| sed 's/\(^0*\|\.\|\-\)//g');;`

by adding in the `|\-\` bit to remove the trailing hyphen.

**Comment by helfrichmichael** [comment]
We've made some adjustments to the way we handle Bazel versioning and are currently ensuring 0.26.*. I'm going to close this issue given that it hasn't received any follow-up in some time.
