### ISSUE TITLE
Running deploy.sh has errors

### ISSUE THREAD

**Issue by templesnr** [google/loaner#16]
hi, I'm trying to build this for the first time - just want to check if I'm heading in the right direction.  I have some warn errors for peer dependencies, what are they, should they be installed, Where from? or, are they ok?

```
npm WARN @angular/flex-layout@5.0.0-beta.13 requires a peer of @angular/core@^5.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN @angular/flex-layout@5.0.0-beta.13 requires a peer of @angular/common@^5.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN @angular/flex-layout@5.0.0-beta.13 requires a peer of rxjs@^5.5.0 but none is installed. You must install peer dependencies yourself.
npm WARN ajv-keywords@3.2.0 requires a peer of ajv@^6.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN gng@0.0.1 No description
npm WARN gng@0.0.1 No repository field.
npm WARN gng@0.0.1 license should be a valid SPDX license expression

up to date in 11.849s
```

Also, the [bootstrapping](https://github.com/google/loaner/blob/master/docs/setup_guide.md#bootstrapping) section in the setup guide mentions:
> so make sure you've added your account to the correct group technical-admins group you defined  previously.

but there is no guidance on the permissions for the technical-admins group setup

**Comment by ericwhiteau** [comment]
Just looking back over my history, but dont have the command set....

I manually installed Angular to clear the dependencies I think.

**Comment by templesnr** [comment]
thank you - it's an absolute nightmare .... I've tried to use install-peerdeps but that just made things worse!  I've run a gcloud init and I'll try again tomorrow.  If anyone can tell me how to get the right Angular peers installed it would be most helpful

**Comment by ericwhiteau** [comment]
As I said I couldnt find it in command history, but it was not a big issue?

I think I only ran

npm install angular

**Comment by ericwhiteau** [comment]
I used Ubuntu  I think because it was the first option when I was reading the install for the tools.  Bazel.

I was also familiar with Ubuntu and Centos.  go with what you know..

cheers.

**Comment by templesnr** [comment]
yep, just tried Debian because I read it was good, but I haven't got on with it very well - there's an issue with Node .. so I'm going back to KDE Neon - I like KDE very much.  That's what I did my first try with, now I'm going to clean things up a bit.  Thank you

**Comment by templesnr** [comment]
the section **shared/config.ts** - says:

> "STANDARD_ENDPOINTS is the Google Endpoints URL the frontend uses to access your backend API. If necessary, update the prod, qa and
> dev values." 
... I'm trying to fathom what I'm supposed to put there, it's quite baffling and I can't home in when searching for it so I'm leaving it unchanged

**Comment by templesnr** [comment]
thank you for persevering with this @ericwhiteau !
the changes to myprojectname were made before the build.  The script seems to be stumbling at the last step, which is:

  ../bazel-bin/loaner/deployments/deploy_impl \
    --loaner_path "$(pwd -P)" \
    --app_servers "${APP_SERVERS}" \
    --build_target "${BUILD_TARGET}" \
    --chrome_app_dir "${CHROME_APP_DIR}" \
    --web_app_dir "${WEB_APP_DIR}" \
    --yaml_files "${SERVICES},${CONFIGS}" \
    "${@}"

It's when executing this that the error on 249 occurs, which is 
  --loaner_path "$(pwd -P)" \

**Comment by Sasho11** [comment]
1. How did you clone the repo down? 

2. Did you install [Bazel](https://docs.bazel.build/versions/master/install.html)?

**Comment by templesnr** [comment]
> 1. How did you clone the repo down?
I downloaded directly from this url: https://codeload.github.com/google/loaner/zip/master then extracted to a folder **~/salsadiary/Dev/loaner-master/loaner**
> 2. Did you install Bazel?
Yes Bazel was installed from **bazel_0.18.1-linux-x86_64.deb**.  I used the instructions at [this link](https://docs.bazel.build/versions/master/install-ubuntu.html#install-with-installer-ubuntu)

**Comment by ericwhiteau** [comment]
I am not an expert (as it worked so I didnt need to unpack it.)

however, as I understand from looking at the setup.  the line before 249

bazel build //loaner/deployments:deploy_impl
creates the set of setup and config files.  (I assumed in the BUILD Directory)  and I assume cleans up.

cheers.

**Comment by templesnr** [comment]
Thank you @ericwhiteau.  No, I'm not an expert, but plenty of experience following cook-books like this.

I've had a look in the folder structure.  There seems to be a mismatch in the folder structure and what deploy.sh is expecting.
deploy.sh is expecting   ../bazel-bin/loaner/deployments/deploy_impl
but that doesn't exist and I actually I have  ../bazel-loaner-master/loaner/deployments/deploy_impl

I changed the line in deploy.sh to my actual path ../bazel-loaner-master/loaner/deployments/deploy_impl \ and re-ran it but it still failed in the same place.

Here's my folder structure below /Home/Dev/loaner-master/
I can see the following tree:
Home/Dev/loaner-master/assets with subfolders
Home/Dev/loaner-master/bazel-bin with no subfolders
Home/Dev/loaner-master/bazel-genfiles with no subfolders
Home/Dev/loaner-master/bazel-loaner-master
Home/Dev/loaner-master/bazel-loaner-master/bin with subfolders
Home/Dev/loaner-master/bazel-loaner-master/bazel-out  with subfolders
Home/Dev/loaner-master/bazel-loaner-master/external with subfolders
Home/Dev/loaner-master/bazel-loaner-master/loaner with subfolders
Home/Dev/loaner-master/bazel-out with subfolders
Home/Dev/loaner-master/bazel-testlogs
Home/Dev/loaner-master/loaner with subfolders

**Comment by templesnr** [comment]
Ah, I think I realised what's happened!  I downloaded the master branch.
I just read the release notes again - I'll try the 0.7 branch.
