### ISSUE TITLE
Bootstrap screen still shows.

### ISSUE THREAD

**Issue by ericwhiteau** [google/loaner#17]
I have been testing and have done two installs.

I have run the bootstrap process successfully and changed the constants.py for Bootstrap = False

However, was still getting the bootstrap redirect in the web app.

### Expected Behaviour
I see in release notes "Known Issues."
If you are constantly redirected to the bootstrap screen you may need to go into Datastore and select "Config" in the dropdown menu and set bootstrap_completed to true.

However, in my config  bootstrap_completed is true.   

I note that bootstrap_started is false.   If I manually set this to true  the webapp performs as expected.

**Comment by dp2sholly** [comment]
Same with an install I ran.  Version 0.7a.  Setting bootstrap_started to "true" resolved.

**Comment by Sasho11** [comment]
dp2sholly is correct. We're aware of an issue where the bootstrap_started setting gets flipped back to false after it is set to true. For now, please manually set it to true by going to appengine datastore and manually editing the datastore entity in the config section. 

![screenshot 2018-11-12 at 9 51 38 am](https://user-images.githubusercontent.com/15381388/48354799-93757f00-e660-11e8-8c7e-26de27cba741.png)

**Comment by helfrichmichael** [comment]
We've pushed from HEAD and the latest changes are available on https://github.com/google/loaner/tree/Alpha-(0.7.1).
