### ISSUE TITLE
Cannot extract App Sign-in or Return survey responses

### ISSUE THREAD

**Issue by jimcollierGF** [google/loaner#24]
### Expected Behaviour
Extpected to be able to Extract user responses from the sign in and return questions.  

### Actual Behaviour
So far I haven't found a way to extract the question responses that users submit.  I've tried with BigQuery and Datastore.  Neither one will show how many time the response options have been selected.  
  
### Steps to Reproduce
Try to extract questions responses.

**Comment by cupajoe24** [comment]
This was a bug that has been fixed at HEAD. If you don't want to pull from HEAD it will also be in the next major release.

**Comment by helfrichmichael** [comment]
We've pushed from HEAD and the latest changes are available on https://github.com/google/loaner/tree/Alpha-(0.7.1).
