### ISSUE TITLE
Super small markdown mistype on G Suite Config docs page

### ISSUE THREAD

**Issue by CoreyGriffin** [google/loaner#29]
### Expected Behaviour
Image for OU structure should have width of 450px

### Actual Behaviour

It's currently showing the image and has `{width="450"}` next to it

### Steps to Reproduce

Go here: https://github.com/google/loaner/blob/master/docs/gsuite_config.md#configure-the-organizational-unit

Might just need to switch it to an `<img>` tag

**Comment by helfrichmichael** [comment]
This has been fixed at head. Thanks for reporting this!
