### ISSUE TITLE
Application not fully loading

### ISSUE THREAD

**Issue by thescott** [google/loaner#3]
### Expected Behaviour
The deployed application should allow me to see the web portal. 
### Actual Behaviour
Blue loading circle that never goes away.  Console error states 
Uncaught wYmessage: "API discovery response missing required fields."stack: "gapi.client.Error: API discovery response missing required fields.↵    at new wY (https://apis.google.com/_/scs/apps-static/_/js/k=oz.gapi.en.3ztcf60wj34.O/m=client/rt=j/sv=1/d=1/ed=1/am=wQ/rs=AGLTcCO1iMQ1m2V7qF5KgDW5wzPda2t5Hw/cb=gapi.loaded_0:672:159)↵    at f (https://apis.google.com/_/scs/apps-static/_/js/k=oz.gapi.en.3ztcf60wj34.O/m=client/rt=j/sv=1/d=1/ed=1/am=wQ/rs=AGLTcCO1iMQ1m2V7qF5KgDW5wzPda2t5Hw/cb=gapi.loaded_0:723:83)↵    at h.r2 (https://apis.google.com/_/scs/apps-static/_/js/k=oz.gapi.en.3ztcf60wj34.O/m=client/rt=j/sv=1/d=1/ed=1/am=wQ/rs=AGLTcCO1iMQ1m2V7qF5KgDW5wzPda2t5Hw/cb=gapi.loaded_0:84:107)↵    at xs (https://apis.google.com/_/scs/apps-static/_/js/k=oz.gapi.en.3ztcf60wj34.O/m=client/rt=j/sv=1/d=1/ed=1/am=wQ/rs=AGLTcCO1iMQ1m2V7qF5KgDW5wzPda2t5Hw/cb=gapi.loaded_0:87:306)↵    at Wq (https://apis.google.com/_/scs/apps-static/_/js/k=oz.gapi.en.3ztcf60wj34.O/m=client/rt=j/sv=1/d=1/ed=1/am=wQ/rs=AGLTcCO1iMQ1m2V7qF5KgDW5wzPda2t5Hw/cb=gapi.loaded_0:87:186)↵    at _.C.uea (https://apis.google.com/_/scs/apps-static/_/js/k=oz.gapi.en.3ztcf60wj34.O/m=client/rt=j/sv=1/d=1/ed=1/am=wQ/rs=AGLTcCO1iMQ1m2V7qF5KgDW5wzPda2t5Hw/cb=gapi.loaded_0:87:52)↵    at Ap (https://apis.google.com/_/scs/apps-static/_/js/k=oz.gapi.en.3ztcf60wj34.O/m=client/rt=j/sv=1/d=1/ed=1/am=wQ/rs=AGLTcCO1iMQ1m2V7qF5KgDW5wzPda2t5Hw/cb=gapi.loaded_0:80:284)↵    at t.invoke (https://onixgrabandgopoc.appspot.com/application.js:1:2143786)↵    at a.run (https://onixgrabandgopoc.appspot.com/application.js:1:2138956)↵    at https://onixgrabandgopoc.appspot.com/application.js:1:2148884"__proto__: _.se

### Steps to Reproduce
I have created a Compute Engine resource that I am using to push to app engine.  When I pull/clone my code to my MacBook I observe the same behavior. 

Should this project be open to the world in order for the site to work properly?

**Comment by cupajoe24** [comment]
Hey, thanks for reporting this. Is there anything showing in the backend logs? You can view them at console.cloud.google.com. Select Logging from the side menu.

**Comment by thescott** [comment]
Hi, Joe thank you for the reply, 
I am not seeing any errors all I can find are notices that the cron job runs which appears to be normal behavior.

**Comment by helfrichmichael** [comment]
So if you attempt to access the web application and then check the logs on console.cloud.google.com, you should see the error as one of the items in the log list (it may take a few seconds to show up). Additionally, does this issue happen before or after you click login on the web app?

**Comment by thescott** [comment]
I am not even presented a login 
I get a nice blue circle when I inspect the page is when I get the data I posted in my initial report.

**Comment by helfrichmichael** [comment]
When you open that page, does anything show up on the console.cloud.google.com logs for the project though?

**Comment by thescott** [comment]
Yes I get logs the only error at the moment is 
No enabled reminder events. loaner/web_app/backend/handlers/cron/run_reminder_events.py:62
Aside from that everything is clean

**Comment by thescott** [comment]
Editing config.ts 
export const PROD = 'prod-app-engine-project';
Needs to be the project name without appspot.com
Also 
API needs to follow the convention.  
qa: `https://endpoints-dot-${QA}.appspot.com`,
