### ISSUE TITLE
Where is the Technical Admins Group?

### ISSUE THREAD

**Issue by templesnr** [google/loaner#34]
### Expected Behaviour
I should be able to define the Technical_Admins_Group to allow access to certain web-app functions
### Actual Behaviour
Technical Admins Group is not defined
### Steps to Reproduce
The code does not contain this group

Hi- I'd like to add the technical admins group (it's mentioned in setup_guide but it does not seem to be in the implementation)

Can someone please confirm whether or not we should set up this group - and where we define it in the setup?

I think I found it in `loaner/web_app/config_defaults.yaml` there's:
`# responsible_for_audit: list, A group that is responsible for performing an`
`# audit on a shelf.`
`'responsible_for_audit': ['technicians@example.com']`
I'll get a group created, try it, and report back

**Comment by David-Promevo** [comment]
Hi,

The technical admins group mentioned is actually just the SUPERADMINS_GROUP
in the constants.py file.  That piece of the documentation probably hasn't
been updated to reflect that.

**Comment by templesnr** [comment]
Hi,  that's OK but I want to give certain users the ability to audit a shelf, nothing more, which is why I was hoping technical-admins would do it. 
Thank you.

**Comment by David-Promevo** [comment]
Ah, gotcha.  I misunderstood.  That group is actually defined in the front-end.  It's under the "Configuration" menu in the shelves section.

**Comment by templesnr** [comment]
Thank you David - I think I know what to do.  In the Web Configuration page, I can see "Group responsible for audit" - hopefully all I have to do is get the group created and then add users to it!
