### ISSUE TITLE
Chrome application not detecting enrollment status

### ISSUE THREAD

**Issue by jholtmann** [google/loaner#36]
### Expected Behaviour

Chrome application launches on-boarding process.

### Actual Behaviour

Chrome applications gives the following error message:
"This device is not enrolled in the Grab N Go program. Please contact your administrator."

### Steps to Reproduce

I followed the installation steps as specified.

It is possible that I missed a step or setting somewhere during the deployment, thereby causing this issue. However, I have read over the steps again and cannot seem to find anything I might have missed. The two Chromebooks I am testing with are both Enterprise Enrolled and enrolled in the Grab N Go program through the web interface. However, when signing in to them, the GrabNGo application gives the above error message.

**Comment by David-Promevo** [comment]
Check the following:

1) In the APP_DOMAINS variable in constants.py, the **primary** GSuite domain should be listed first and any secondary domains listed after.  If that is not the case, fix, redeploy, migrate traffic.

2) Double check the deployment files to ensure you are using the correct Client ID.  The Chrome App ITEM ID from the Chrome Web Store App may be incorrectly placed where Chrome App OAUTH client ID should have been.  The Chrome App ITEM ID should **not** be added to any of the deployment files.  If that is the case, fix, redeploy, migrate traffic.

3) Check that the OAuth Consent Screen is set to "Public". GCP > API > Credentials > OAuth Consent Screen.

If all those look good, check the output from the following:

(On the Chromebook) Chrome://extensions ---> Dev Mode on > background page > Reproduce > Check Console Section in background.html / index.html
or 
(On the Chromebook) Chrome://extensions ---> Dev Mode on > Details > Toggle on Error Reporting > Reproduce > Check Error Section

**Comment by scassidy01** [comment]
I have the same issue. Went through everything multiple times and now am having the "This device is not enrolled in the Grab N Go program. Please contact your administrator." error as well.

Device is enterprise enrolled and is in the **_Org > Grab n Go > Prod_** OU

**Comment by templesnr** [comment]
Asking the obvious - the devices must be enrolled in device management AND
in the specified GRab n Go OU AND enrolled (added) to the Loaner devices
via the Grab n Go Web devices page ???.appspot.com/devices  I have
occasionally forgotten the last step.

Temple

**Comment by scassidy01** [comment]
@templesnr yeah that's exactly what I have setup. I checked the BigQuery table and it's showing that the devices have been enrolled in to GnG.

It gives me the error instantly which is odd. It's like it's not even going outbound to check if it's actually enrolled.

**Comment by helfrichmichael** [comment]
Have you checked the debug view CTRL + SHIFT + 9? If so, please share a screenshot so we can attempt to troubleshoot further. Additionally, is there any logs in GCP for the heartbeat from this device?

**Comment by scassidy01** [comment]
I'm seeing NULL in the heartbeat column on BigQuery...

![Screen Shot 2019-04-03 at 2 35 46 PM](https://user-images.githubusercontent.com/19437103/55504141-359d0000-561e-11e9-822e-083a58a67afa.png)

**Comment by helfrichmichael** [comment]
I would recommend against using BigQuery for debugging issues such as these. StackDriver logging (Logging option on Google Cloud Platform) will provide fairly in-depth info about what is happening when requests are made. Additionally, any luck in grabbing a screenshot from the debug view (CTRL+SHIFT+9 on the Chromebook you're having issues with)?

**Comment by scassidy01** [comment]
Pardon my ignorance... Where am I launching debug mode? The application just fires off a notification when I launch it. I've enabled error logging on the extension and here's what I see.

![Screenshot 2019-04-03 at 3 04 49 PM](https://user-images.githubusercontent.com/19437103/55505941-46e80b80-5622-11e9-87a4-2a5970708391.png)

And the notification:
![Screenshot 2019-04-03 at 3 05 52 PM](https://user-images.githubusercontent.com/19437103/55505960-4f404680-5622-11e9-8b8d-0162f690acc1.png)

**Comment by helfrichmichael** [comment]
Do you see any heartbeat requests on StackDriver? It's possible you've misconfigured the loaner/shared/config.ts if there are no heartbeats making it to the backend. Additionally, which version of the application are you running? This one looks like it's out-of-date considering that the notification doesn't include a "DEBUG" button.

My recommendation would be to pull the latest version from HEAD (latest commit to the master branch). Once you do this, make sure all your configured values are properly set once again and then update the web app and Chrome App. 

If you're still hitting this issue after updating, you can launch the debug view doing CTRL+SHIFT+9 from the Chrome OS device with the Grab and Go application installed.

**Comment by scassidy01** [comment]
@helfrichmichael Figured I'd let you know I got this working. I think my issue was more of a timing thing and wasn't being patient with things propagating on the chrome dev dashboard side.

**Comment by akshitbaunthy** [comment]
Similar issue here. Some devices do not detect enrollment status. These devices are in the Default OU (ChromeOS -> Grab n Go -> Prod -> Default) and are enrolled in the program as well.
One thing I noticed is that they do not have a heartbeat (last_heartbeat is null). There are several devices that work just fine.
One thing to note here is - The version running is 0.7.1. I will be updating this to latest master to check.
Do we have any insight on what might be the issue?
![last_heartbeat](https://user-images.githubusercontent.com/50140727/58625119-66807500-82ef-11e9-91f6-b18aba04678d.png)

**Comment by akshitbaunthy** [comment]
Okay. So I went ahead and deployed the master version of the app. I think I have a handle on the error now. The Chrome app is requesting the URL https://chrome-dot-dev-app-engine-project.appspot.com
I used bash to deploy the web app using deploy.sh for prod (**deployments/deploy.sh web prod**) and used **bash deployments/deploy.sh chrome prod** to deploy the chrome app.
Any pointers here?
![404](https://user-images.githubusercontent.com/50140727/59348506-f0d7c880-8d34-11e9-8e5f-96efa471a351.png)

**Comment by helfrichmichael** [comment]
@akshitbaunthy this means you haven't configured the shared/config.ts file.

Please see: https://github.com/google/loaner/blob/master/docs/setup_guide.md#sharedconfigts and https://github.com/google/loaner/blob/master/docs/deploy_chrome_app.md#step-3-keying-the-chrome-app specifically step #5.

This means that in your config.ts, you haven't defined your endpoints (it's pointing to the default dev instance). If you are expecting it to be pointing at PROD right now, that additionally means that you likely haven't configured the CHROME_PUBLIC_KEYS for each environment. This is how the application figures out which release track it is on. 

As for deploying, I typically build the chrome app using NPM, zip up the directory, and upload it as a new version of the existing app to the Chrome Web Store.

**Comment by akshitbaunthy** [comment]
@helfrichmichael - Thank you for your response.
I checked and you were right. The CHROME_PUBLIC_KEY was incorrect. I screwed up line breaks. Fixed it, compiled both the web and chrome apps. Awaiting propagation.
Just wondering though, is that the only thing that can cause this? Since the error actually points to chrome-dev and I haven't put in ANY details for any of the other instances.

**Comment by helfrichmichael** [comment]
You have to define the name of the appengine instance you're trying to hit
in the config.ts. Otherwise all requests will fail since it can't phone
home.

**Comment by akshitbaunthy** [comment]
Yup. Thanks a tonne, @helfrichmichael.

**Comment by helfrichmichael** [comment]
Great to hear @akshitbaunthy. I'll mark this as closed, but don't hesitate to let us know if you're having any further issues.
