### ISSUE TITLE
Problems auditing a shelf

### ISSUE THREAD

**Issue by JoshSanchezG** [google/loaner#40]
### Expected Behaviour
When we audit a shelf all serial numbers added to the audit page should remove the pending status.

### Actual Behaviour
Just one device is not removing this status (pending to return).

### Steps to Reproduce
When you log into a GnG device, close the GnG wizard and don't define the return date. Important we have define the default loan duration as 2 days in the web app settings.

Thank you.

**Comment by kid-yume** [comment]
Good Afternoon, 

       Im confused as to the issue. You are unable to return the device; due to the default return date never taking place, because of closing the wizard prematurely. Correct?

**Comment by helfrichmichael** [comment]
Going to resolve this since there hasn't been any further update in some time. Thanks and let us know if this isn't resolved.
