### ISSUE TITLE
We enabled ephemeral mode in the OU for the Chromebooks but the previous user's login being used for the wifi connection

### ISSUE THREAD

**Issue by wavehunter** [google/loaner#48]
### Steps to Reproduce - For a Pixelbook which we have registered with the GnG system we have test user1 login to the device. It all works as expected and then the user goes to return the Pixelbook. They go through the steps with the GnG client application to submit the device to be returned. They logout of the Pixelbook.

Next user, test user2 gets the same Pixelbook. They turn it on and go through the GnG client app intro steps. No problem. They do some work, etc .... seems fine. But upon reviewing the device's 
wifi config settings we can see the login being used to connect to the corporate wifi network is using user1 credentials. This is a security flaw and could lead to misidentifying an incorrect users activity on our internal network.

From some brief research it seems like we may have a misconfiguration for the network settings on the OU which the devices are assigned ... just not sure. Any advice appreciated.

Thanks,
Bob

**Comment by wavehunter** [comment]
Quick update: we updated the following setting - Device management/Chrome/Device Settings/User Data field to <Erase all user data>. Initially testing still shows previous users wifi network settings (login/pw) being used.

Please let us know if you have any input or suggestions. Thanks

**Comment by kid-yume** [comment]
Good Afternoon, 
   I am curious as to if only the Grab n Go devcies are experiencing this issue? IF you have devices in outside the Grab n Go OU experiencing the same issues?

**Comment by wavehunter** [comment]
Hi - Only the Grab n Go devices. The others are allowed to sign on to the wireless network as themselves and then they use only that same device .. unless they turn it it later and it gets power washed.

**Comment by helfrichmichael** [comment]
We have no control over this as this is derived in Chrome OS and Google Admin itself. I'd recommend filing feedback via Chrome OS or other channels like Google Admin if this is a concern for your organization. I'm going to resolve given that there is nothing we can do about this. Let me know if you have any further questions.
