### ISSUE TITLE
Devices are visible on all Shelves

### ISSUE THREAD

**Issue by templesnr** [google/loaner#50]
### Expected Behaviour
Create shelves and assign devices to them
View all the devices that are assigned to a shelf
Audit each shelf's devices
### Actual Behaviour
I can create shelves
** when I view a shelf, it shows all enrolled devices, including devices on other shelves **
I can audit the devices
### Steps to Reproduce
enrol devices
Create two shelves
assign devices to shelves
view shelf details

### observation ###
we have over seventy Grab 'n Go devices now - shelf management is an issue.  This is what I understand:

1. Assign device to shelf by "audit shelf"
2. Check device out by signing in as a user
3. Grab 'n Go then removes the device from the shelf

The logic above, in our case, doesn't quite fit.  We'd prefer for the device -> shelf relationship to remain in place until the device has been returned.  We have six shelves so far, the shelf belongs to a team, so the team has access to a pool of devices, which are returned to the same shelf when the person has finished with it.

Thinking about Google's use case, I can understand that perhaps Google doesn't really care which shelf goes back to - the user is known and once the user has the device it isn't on a shelf - then the device gets audited when it's on a shelf anywhere.

It makes sense, to me, that the device -> shelf relationship could be updated only when the device is audited on the shelf, rather than being removed when the user signs-in to the device

**Comment by kid-yume** [comment]
So you would like the device Shelf relationship to continue after the user signs in? Would adding a field like "Shelf Checked Out From" Help and accomplish what you would like to see?

**Comment by templesnr** [comment]
Hi @kid-yume - what you suggest makes sense.  Bearing in mind we aren't auditing shelves, we assume that the device will be returned to the same shelf.  We will have no way of knowing where the device is between loans.  If the device is returned to a different shelf then we won't know unless the device has been audited on its new shelf.

**Comment by gyoshi02** [comment]
Not sure if this is similar. 
I'm also seeing duplicate devices on other shelfs. 
I'm also having an issue where I can't remove an older shelf we were just testing. 
I tried to remove it from the console, and also may have removed a table from Big Query (I know that was going to far) 

![image](https://user-images.githubusercontent.com/45863342/64875318-b1559c80-d601-11e9-9958-2713ec41e78e.png)
![image](https://user-images.githubusercontent.com/45863342/64875405-e7931c00-d601-11e9-9acc-7580f354fff7.png)

Is there any advice you can offer to allow Removal of Shelf? 
Or is there a way to start over, and clear out your devices and Shelves? 

We only have 2 Shelves and 10 devices enrolled in this pilot. 
thanks,

**Comment by kid-yume** [comment]
If removed from Big Query please be sure to clear your mem cache found in: console.cloud.com > Appengine>memcahe>flush Cache 

Following that, go to your Grab n Go Web Admin Configuration page. reindex devices and shelves. 

Be sure when creating Shelves that you are using unique Locations and friendly names. Even if they are in the same location

**Comment by helfrichmichael** [comment]
Going to resolve this since there hasn't been any further update in some time. Thanks and let us know if this isn't resolved.
