### ISSUE TITLE
Entities Questions have gone, how can I restore them?

### ISSUE THREAD

**Issue by JoshSanchezG** [google/loaner#51]
I did some changes in the bootstrap.yaml (emails templates and surveys), before the deploy I had this:

![x](https://user-images.githubusercontent.com/43448488/57017658-addaef00-6be5-11e9-8534-a226bfe2e18d.png)

but now, I do not have them:

![Screenshot 2019-04-30 at 08 36 19](https://user-images.githubusercontent.com/43448488/57017701-e8448c00-6be5-11e9-933d-ea05b952c2d2.png)

The chrome web app is not showing the survey:

![Screenshot 2019-04-29 at 13 28 17](https://user-images.githubusercontent.com/43448488/57017728-05795a80-6be6-11e9-9195-e9e702b93599.png)

Do you have any idea how to create them again? I have tried bootstrapping the app more than 10 times and it's not working, also I tried to create the 2 entities manually but I think I'm doing wrongly (type of data, names, etc).

![Screenshot 2019-05-01 at 07 53 15](https://user-images.githubusercontent.com/43448488/57017773-322d7200-6be6-11e9-95c2-00e817eda207.png)

Thank you in advance for your help and suggestions.

**Comment by kid-yume** [comment]
Josh, 
    I see your having issues. It seems like the questions were not read properly. Do you mind if you could share your Yaml file of the edits you made to the "survey_questions" list item?

**Comment by JoshSanchezG** [comment]
Hi Aaron,

  I did some changes using a Chromebook, I was sure that I kept the correct extension (.yaml) but after the bootstrap process, I did not see the question entities in the GCP, after that I tried with the original file (I had a backup file).

  I have been thinking on 2 options but I'm not sure if that could work:
1) Create the entities manually (but I will need a screenshot of each one and in addition a screenshot of each value... :(
2) To do "something" in the web_app folder in order to reset the project and load the default bootstrap.yaml file.

Do you have any idea or suggestion?

Thank you in advance.

PS. I'm not adding the .yaml file because that I used the original one and I did not see the entities.

**Comment by gng-demo** [comment]
The way the code is written, it takes in that list. If its not reading anything anymore. I am curious as to see if either the syntax is off, and potentially have you made sure you are on the most up date versioning as well, correct? Could you potentially remove the question you added or use the original yaml file and see if the change takes place?

**Comment by JoshSanchezG** [comment]
Hi fellas,

  I used the master version from the beginning, I used the modified bootstrap.yaml file (with the new questions), I did build the web app and the chrome app, I uploaded the new chrome app version to "Web Store Developer Dashboard", I selected the new version of each service and I waited for more than 24 hrs. Now the 2 Question entities are in the GCP.

Thank you for all.
