### ISSUE TITLE
ERROR: get_user_email failed: No user account detected.

### ISSUE THREAD

**Issue by ryantuck** [google/loaner#54]
### Expected Behaviour

1. Follow instructions for deploying web app
2. Successfully deploy web app
3. Navigate to web app via GCP console and not encounter errors.

### Actual Behaviour

Navigate to web app via GCP console and encounter the following error immediately upon opening page:

```
ERROR: get_user_email failed: No user account detected.
```

### Steps to Reproduce

1. Clone branch `Alpha-(0.7.1)`
2. Install `bazel v0.24.1`, because `v0.25` will not deploy correctly (this is specified in [.travis.yml](https://github.com/google/loaner/blob/master/.travis.yml))
3. Follow instructions for creating GCP roles, service accounts, Oauth2 client ids, etc.
4. Follow instructions for updating `shoared/config.ts` and `web_app/constants.py` in the appropriate places, assuming a `prod`-only deployment (i.e. no changes to QA or dev variables).
5. Deploy successfully.
6. Go to GCP > App Engine > Versions, route all traffic to deployed version of app, and navigate to `https://<project-id>.appspot.com`
7. See error message at bottom of page: `ERROR: get_user_email failed: No user account detected.`

One thing to note is that we had to make the following change _not_ mentioned in the setup guide in order to ensure deploys work, for what it's worth:

In `loaner/deployments/deploy.sh`

```
-  ../bazel-out/k8-py3-fastbuild/bin/loaner/deployments/deploy_impl \
+  ../bazel-out/darwin-py3-fastbuild/bin/loaner/deployments/deploy_impl \
```

We've given the `ADMIN_EMAIL` role account super admin access to avoid any permissions-related issues, but still receive the error.

Any guidance would be appreciated. One hypothesis I have yet to test is changing the bazel version to `0.11.1` as is is specified in the `Alpha-(0.7.1)` branch's `.travis.yml` file, though I'm not familiar enough with App engine to determine whether this would be the issue (since deploys go out just fine, I'm assuming that `bazel` would _not_ be the culprit here).

cc @cadiealys

**Comment by David-Promevo** [comment]
Make sure in your constants.py file that you do not have the brackets around your admin email.

The variable initially looks like this:

    ADMIN_EMAIL = '{ADMIN_EMAIL}'

Remove the braces and just put the admin email in the quotes.

**Comment by cadiealys** [comment]
Confirming that we did remove the brackets around `ADMIN_EMAIL` so that doesn't seem to be the issue here.

**Comment by gng-demo** [comment]
Your Endpoint is not receiving the proper account. I am thinking. Please go into the debugging of the App Engine.  The same place where the versioning is of the App Engine. You can click the drop-down to right and select the "debug" option

**Comment by cadiealys** [comment]
@gng-demo Thanks for this! I was able to pinpoint the issue when going into the logs to send them over. We're up and running! (Needed to deploy a version of the app with the same name as the original version we had deployed and since deleted.)

**Comment by ryantuck** [comment]
Cool yeah, I'm happy to close this out since we got the issue resolved. Thank you for the quick replies everyone!
