### ISSUE TITLE
Actual G Suite Admin Role Permissions Required (To Reduce Security Risk)

### ISSUE THREAD

**Issue by chromestrong** [google/loaner#56]
### Overview
Enterprise security team will not allow the loaner-role proxy G Suite account to have G Suite admin role permissions it actually doesn't need.  A custom GnG Admin G Suite role is needed.

The security team doesn't care that the account will not be logged into by a human, it must only use what it needs.

### Expected Behaviour
Documentation for GnG gives you the option to add pre-set G Suite admin roles OR create a custom G Suite Admin role for GnG to be more secure.

### Actual Behaviour
In step 3 of the setup document you are told to add the following roles to the loaner-role@example.com account.

Directory Admin ( Doesn't exist )
Services Admin
User Management Admin

### Steps to Reproduce
Setup Grab In Go, get to Step 3

**Comment by templesnr** [comment]
This shouldn't be an issue if the instructions are followed correctly as
nobody should know the password and 2-factor authentication.  The existing
Superadmins are a greater threat.  Also the loaner account can be audited
more frequently if they really think they need to.
For directory admin - it's actually groups admin; that is noted in an
earlier thread.

I would be interested to hear what the developers say on the loaner-role
account.

**Comment by chromestrong** [comment]
It has been communicated that this account isn't suppose to be used by a human ever and that its password would be unknown and it would have 2FA attached to it.  However, the issue remains that the roles have additional permissions that the loaner-role account doesn't need and we cannot move forward with a deployment of Grab N Go until we discover the exact permissions that are required to create a custom GnG Admin account.

**Comment by githerbert** [comment]
You can test this yourself.  Deploy on a sandbox domain, add all documented permissions and remove one at a time until you find the minimum needed.

**Comment by helfrichmichael** [comment]
This seems to be a dupe of #4. I'm going to resolve this in favor of that bug.
