### ISSUE TITLE
Grab N Go - Chrome App stuck on 'We are checking devices current status'

### ISSUE THREAD

**Issue by damionwilliams** [google/loaner#59]
When launching the GrabNGo application on a Chromebook the application should check to see the current status based on the GrabNGo website.

The ChromeApp just sits forever at 
We are checking devices current status
![image](https://user-images.githubusercontent.com/26466032/61371647-253b2900-a88d-11e9-92aa-468ab3a6b7ff.png)

Debug screen reports this:

![image](https://user-images.githubusercontent.com/26466032/61371682-44d25180-a88d-11e9-84fe-f31b2d414902.png)

I've added the Chrome client ID to the Admin Console:

![image](https://user-images.githubusercontent.com/26466032/61371790-7d722b00-a88d-11e9-86cf-9376cfb681b4.png)

Any assistance anyone can offer would be greatly appreciated!

Thanks
Damion

**Comment by helfrichmichael** [comment]
Thanks for attaching the debug screen. It looks like the OAuth setup wasn't finished. In the Chrome App's manifest.json (https://github.com/google/loaner/blob/master/loaner/chrome_app/manifest.json), there's a field called "client_id" is that defined with the same Client ID that is attached in the last screenshot?

**Comment by damionwilliams** [comment]
Thank you Michael for the quick response sir!

  },
  "description": "Start and manage your GnG experience here!",
  "icons": {
    "128": "assets/icons/gng128.png",
    "16": "assets/icons/gng16.png",
    "48": "assets/icons/gng48.png"
  },
  "key": "******************************************************************************************************************************************************************************************************IDAQAB",
  "manifest_version": 2,
  "name": "GnG Loaner App",
  "oauth2": {
    "client_id": "*************************************************psfb3t.apps.googleusercontent.com",
    "scopes": [
      "https://www.googleapis.com/auth/userinfo.email"
    ]
  },

So it should be the same, this is the new compiled Chrome app that was uploaded to the webstore, key and client_id are the same! This is a complex piece of software :)

**Comment by helfrichmichael** [comment]
Do you mind doing the following?

**On Google Admin:**

Go to Chrome Management
Manage User Settings
Find the OU which is pushing the Grab n Go application.
Search for the "Developer Tools" drop-down menu.
Switch it to "Always allow use of built-in developer tools".
(The settings above you can enable temporarily or leave permanently. We enable developer tools access for all apps/extensions on the Google domain FWIW.)

**On the Chromebook with GnG installed:**

Go to chrome:extensions in a new Chrome tab.
Enable developer mode on the top right.
Scroll to the Grab n Go app and click the "background page" hyperlink.
Confirm if there are any errors or warnings in the console (you may need to logout and log back in if nothing is there).

Additionally, if you don't mind confirming, is the manifest.json matching what is in your dist/ folder for the chrome_app?

**Comment by damionwilliams** [comment]
Thanks again Michael.

I believe I removed the /dist folder from the chrome_app folder on the server, I honestly cant remember why I did this but I did. I perhaps got confused with the requirement to remove key.pem from there. I've copied it back there now.

I am not seeing a 'background page' hyper link in the app when I navigate to extensions. This could be part of the issue

[chrome_app-root-folder-manifiest.txt](https://github.com/google/loaner/files/3402204/chrome_app-root-folder-manifiest.txt)
[webstore-uploadedzip-manifest.txt](https://github.com/google/loaner/files/3402205/webstore-uploadedzip-manifest.txt)

**Comment by helfrichmichael** [comment]
You may need to visit chrome:policy and click "Reload policies" to pull the latest policy set. The developer options button should look like this. Once that's enabled, you'll be able to see the 'background page' link.

![image](https://user-images.githubusercontent.com/9116898/61384507-b951c400-a87e-11e9-8217-6ec09501426e.png)

**Comment by damionwilliams** [comment]
I saw a Error button in extensions, this must appear after the app times out perhaps? Although there is still no hyper link!

![image](https://user-images.githubusercontent.com/26466032/61387070-4dd31b00-a8ad-11e9-98fe-bd07b5c1b38e.png)

So something somewhere does not like my client id!

**Comment by helfrichmichael** [comment]
Based on that error, I think there may be a misconfiguration in your OAuth 2.0 client id's. On GCP, when you visit the API/Credentials page, can you confirm that the Client ID you are using is of type "Chrome App" and additionally, that the Application ID is set to the same Chrome Webstore app ID?

Additionally, can you please confirm that your OAuth consent screen "Application type" is set to "Public"? Feel free to attach any relevant screenshots (assuming you can sanitize the sensitive info on it) as this may help us with debugging further.

**Comment by damionwilliams** [comment]
Thanks Michael, it was the webstore ID. I started again on that and had an entirely different one here: 
![image](https://user-images.githubusercontent.com/26466032/61393138-39e0e680-a8b8-11e9-852c-668c70a00b0b.png)

Updated this and all was well. Will continue trying to bring it online now!

Thanks a lot,
Damion

**Comment by helfrichmichael** [comment]
We haven't heard back from your or others on this issue in a while so I'm going to resolve. Let us know if you're still having issues.
