### ISSUE TITLE
deploy.sh fails on webpack

### ISSUE THREAD

**Issue by carlosjourdan** [google/loaner#60]
When running the deploy.sh script, I hit the following errors after the webpack --config web_app/frontend/config/webpack.aot.js command runs. Any ideas on how to proceed?

ERROR in shared/components/loan_management/loan_actions_card/loan_actions_card.ts(62,32): error TS2345: Argument of type '{ static: boolean; }' is not assignable to parameter of type '{ read?: any; }'.
  Object literal may only specify known properties, and 'static' does not exist in type '{ read?: any; }'.
shared/components/loan_management/loan_actions_card/loan_actions_card.ts(63,31): error TS2345: Argument of type '{ static: boolean; }' is not assignable to parameter of type '{ read?: any; }'.
  Object literal may only specify known properties, and 'static' does not exist in type '{ read?: any; }'.
chrome_app/src/app/shared/chrome_app_platform_location.ts(45,15): error TS2304: Cannot find name 'unknown'.
chrome_app/src/app/manage/app.ts(47,28): error TS2345: Argument of type '{ static: boolean; }' is not assignable to parameter of type '{ read?: any; }'.
  Object literal may only specify known properties, and 'static' does not exist in type '{ read?: any; }'.
chrome_app/src/app/manage/shared/bottom_nav/bottom_nav_test.ts(66,35): error TS2345: Argument of type '{ static: boolean; }' is not assignable to parameter of type '{ read?: any; }'.
  Object literal may only specify known properties, and 'static' does not exist in type '{ read?: any; }'.
chrome_app/src/app/manage/status/status_test.ts(110,47): error TS2304: Cannot find name 'AnyDuringJasmineTypesMigration'.
chrome_app/src/app/manage/status/status_test.ts(113,49): error TS2304: Cannot find name 'AnyDuringJasmineTypesMigration'.
chrome_app/src/app/manage/status/status_test.ts(115,49): error TS2304: Cannot find name 'AnyDuringJasmineTypesMigration'.
chrome_app/src/app/manage/status/status_test.ts(118,49): error TS2304: Cannot find name 'AnyDuringJasmineTypesMigration'.
chrome_app/src/app/manage/status/status_test.ts(121,47): error TS2304: Cannot find name 'AnyDuringJasmineTypesMigration'.
shared/components/return_instructions/return_instructions.ts(34,34): error TS2345: Argument of type '{ static: boolean; }' is not assignable to parameter of type '{ read?: any; }'.
  Object literal may only specify known properties, and 'static' does not exist in type '{ read?: any; }'.
chrome_app/src/app/offboarding/app.ts(88,35): error TS2345: Argument of type '{ static: boolean; }' is not assignable to parameter of type '{ read?: any; }'.
  Object literal may only specify known properties, and 'static' does not exist in type '{ read?: any; }'.
chrome_app/src/app/offboarding/app.ts(90,42): error TS2345: Argument of type '{ static: boolean; }' is not assignable to parameter of type '{ read?: any; }'.
  Object literal may only specify known properties, and 'static' does not exist in type '{ read?: any; }'.
chrome_app/src/app/offboarding/app.ts(99,32): error TS2345: Argument of type '{ static: boolean; }' is not assignable to parameter of type '{ read?: any; }'.
  Object literal may only specify known properties, and 'static' does not exist in type '{ read?: any; }'.
chrome_app/src/app/offboarding/app.ts(100,41): error TS2345: Argument of type '{ static: boolean; }' is not assignable to parameter of type '{ read?: any; }'.
  Object literal may only specify known properties, and 'static' does not exist in type '{ read?: any; }'.
chrome_app/src/app/offboarding/app.ts(104,28): error TS2345: Argument of type '{ static: boolean; }' is not assignable to parameter of type '{ read?: any; }'.
  Object literal may only specify known properties, and 'static' does not exist in type '{ read?: any; }'.
chrome_app/src/app/onboarding/welcome/welcome.ts(29,35): error TS2345: Argument of type '{ static: boolean; }' is not assignable to parameter of type '{ read?: any; }'.
  Object literal may only specify known properties, and 'static' does not exist in type '{ read?: any; }'.
chrome_app/src/app/onboarding/app.ts(87,35): error TS2345: Argument of type '{ static: boolean; }' is not assignable to parameter of type '{ read?: any; }'.
  Object literal may only specify known properties, and 'static' does not exist in type '{ read?: any; }'.
chrome_app/src/app/onboarding/app.ts(89,42): error TS2345: Argument of type '{ static: boolean; }' is not assignable to parameter of type '{ read?: any; }'.
  Object literal may only specify known properties, and 'static' does not exist in type '{ read?: any; }'.
chrome_app/src/app/onboarding/app.ts(96,33): error TS2345: Argument of type '{ static: boolean; }' is not assignable to parameter of type '{ read?: any; }'.
  Object literal may only specify known properties, and 'static' does not exist in type '{ read?: any; }'.
chrome_app/src/app/onboarding/app.ts(98,32): error TS2345: Argument of type '{ static: boolean; }' is not assignable to parameter of type '{ read?: any; }'.
  Object literal may only specify known properties, and 'static' does not exist in type '{ read?: any; }'.
chrome_app/src/app/onboarding/app.ts(99,32): error TS2345: Argument of type '{ static: boolean; }' is not assignable to parameter of type '{ read?: any; }'.
  Object literal may only specify known properties, and 'static' does not exist in type '{ read?: any; }'.
chrome_app/src/app/onboarding/app.ts(100,41): error TS2345: Argument of type '{ static: boolean; }' is not assignable to parameter of type '{ read?: any; }'.
  Object literal may only specify known properties, and 'static' does not exist in type '{ read?: any; }'.
chrome_app/src/app/onboarding/app.ts(104,28): error TS2345: Argument of type '{ static: boolean; }' is not assignable to parameter of type '{ read?: any; }'.
  Object literal may only specify known properties, and 'static' does not exist in type '{ read?: any; }'.
chrome_app/src/app/onboarding/return/return_test.ts(101,47): error TS2304: Cannot find name 'AnyDuringJasmineTypesMigration'.
web_app/frontend/src/components/search_box/search_box.ts(67,28): error TS2345: Argument of type '{ static: boolean; }' is not assignable to parameter of type '{ read?: any; }'.
  Object literal may only specify known properties, and 'static' does not exist in type '{ read?: any; }'.
web_app/frontend/src/components/search_box/search_box.ts(68,39): error TS2345: Argument of type '{ static: boolean; }' is not assignable to parameter of type '{ read?: any; }'.
  Object literal may only specify known properties, and 'static' does not exist in type '{ read?: any; }'.
web_app/frontend/src/components/shelf_actions/shelf_actions.ts(43,35): error TS2345: Argument of type '{ static: boolean; }' is not assignable to parameter of type '{ read?: any; }'.
  Object literal may only specify known properties, and 'static' does not exist in type '{ read?: any; }'.
web_app/frontend/src/views/shelf_actions_view/shelf_actions_view.ts(35,30): error TS2345: Argument of type '{ static: boolean; }' is not assignable to parameter of type '{ read?: any; }'.
  Object literal may only specify known properties, and 'static' does not exist in type '{ read?: any; }'.
web_app/frontend/src/views/device_actions_view/device_actions_view.ts(41,39): error TS2345: Argument of type '{ static: boolean; }' is not assignable to parameter of type '{ read?: any; }'.
  Object literal may only specify known properties, and 'static' does not exist in type '{ read?: any; }'.
web_app/frontend/src/components/device_action_box/device_action_box.ts(73,33): error TS2345: Argument of type '{ static: boolean; }' is not assignable to parameter of type '{ read?: any; }'.
  Object literal may only specify known properties, and 'static' does not exist in type '{ read?: any; }'.
web_app/frontend/src/components/device_action_box/device_action_box.ts(74,31): error TS2345: Argument of type '{ static: boolean; }' is not assignable to parameter of type '{ read?: any; }'.
  Object literal may only specify known properties, and 'static' does not exist in type '{ read?: any; }'.
web_app/frontend/src/components/device_action_box/device_action_box.ts(75,27): error TS2345: Argument of type '{ static: boolean; }' is not assignable to parameter of type '{ read?: any; }'.
  Object literal may only specify known properties, and 'static' does not exist in type '{ read?: any; }'.
web_app/frontend/src/components/device_action_box/device_action_box.ts(76,29): error TS2345: Argument of type '{ static: boolean; }' is not assignable to parameter of type '{ read?: any; }'.
  Object literal may only specify known properties, and 'static' does not exist in type '{ read?: any; }'.
web_app/frontend/src/components/device_list_table/device_list_table.ts(62,24): error TS2345: Argument of type '{ static: boolean; }' is not assignable to parameter of type '{ read?: any; }'.
  Object literal may only specify known properties, and 'static' does not exist in type '{ read?: any; }'.
web_app/frontend/src/components/shelf_list_table/shelf_list_table.ts(53,24): error TS2345: Argument of type '{ static: boolean; }' is not assignable to parameter of type '{ read?: any; }'.
  Object literal may only specify known properties, and 'static' does not exist in type '{ read?: any; }'.

**Comment by carlosjourdan** [comment]
My environment is as follows
Ubuntu 18.04 running on Windows Subsystem for Linux
Bazel 0.28.1
Node v12.8.0
NPM 6.10.2

**Comment by githerbert** [comment]
Downgrade your bazel version to 22.

**Comment by carlosjourdan** [comment]
@githerbert if I do that I get the following error:

ERROR: The bazel version installed is lower than the minimum required version (0.28.0), please update bazel.

**Comment by githerbert** [comment]
What version are you pulling from?  .71a or master?

**Comment by carlosjourdan** [comment]
I was pulling from master by mistake. Now I pulled from .71a and am able to build using bazel 22.

However, I still get the error below when running webpack:

Error: ENOENT: no such file or directory, open '/mnt/c/Users/carlo/Workspace/loaner0.7.1a/loaner/web_app/frontend/dist/assets/search_help.md'

**Comment by carlosjourdan** [comment]
I started from scratch and it worked. Thanks for the help.
