### ISSUE TITLE
Chrome app stuck on 0.0.1

### ISSUE THREAD

**Issue by carlosjourdan** [google/loaner#61]
If I go to chrome://extensions, it shows that the 0.0.1 version is installed. I can see the 0.0.2 if I open the extension locally and click on "view on chrome web store", but it doesn`t seem to be picking that up. Any ideas why this might be happening?

Application is stuck on "we are checking this devices current status".

**Comment by carlosjourdan** [comment]
Never mind, eventually it updated

**Comment by carlosjourdan** [comment]
Reopening this. When I install from store, I get 0.0.2, but the app fails with a console message saying that there is no device ID because it wasn't installed by an admin. If I install from admin console, I get 0.0.1

**Comment by carlosjourdan** [comment]
I uploaded a version 0.0.3 to the store and now 0.0.2 was installed. Is there any config I need to make to mark a publication as stable or something?

**Comment by helfrichmichael** [comment]
I'm going to close this issue in favor of https://github.com/google/loaner/issues/64. You can follow that issue for updates.
