### ISSUE TITLE
"Device XXX is not enrolled in application" when auditing a shelf

### ISSUE THREAD

**Issue by carlosjourdan** [google/loaner#64]
When auditing a shelf, after I type the serial number of the device and press the "+" symbol, it is added to the list with a red exclamation mark saying that the device is not enrolled. 

The device is enrolled and listed on the device list with a "pending return" status.

**Comment by helfrichmichael** [comment]
Can you confirm how many times that device appears in the datastore for the device entities on Google Cloud Platform?

**Comment by carlosjourdan** [comment]
I see to entries with the same serial number, but two different ids.

One of them has the current_ou set to "Grab n Go/Prod/Default" (with enrolled=true), and the other just "/Grab n Go" (enrolled=false).

**Comment by carlosjourdan** [comment]
After deleting the entries from the Device datastore and reindexing the query results everything is working fine.
