### ISSUE TITLE
Bazel Error Build

### ISSUE THREAD

**Issue by gauthier1997** [google/loaner#67]
### Expected Behaviour
Build With no errors

### Actual Behaviour
`/loaner/loaner$ bash deployments/deploy.sh web prod
INFO: Checking for gcloud on PATH and version...
SUCCESS: gcloud was found on PATH and is at or above the minimum version.
INFO: Checking for bazel on PATH and version...
Extracting Bazel installation...
Starting local Bazel server and connecting to it...
SUCCESS: bazel was found on PATH and is at or above the minimum version.
INFO: Checking for npm on PATH and version...
SUCCESS: npm was found on PATH and is at or above the minimum version.
INFO: Checking gcloud authentication...
INFO: Going to the loaner directory...
INFO: Initiating the build of the python deployment script...
ERROR: /home/gauthier_hubert/.cache/bazel/_bazel_gauthier_hubert/5b1014468b822716d4cb420dac37de95/external/io_bazel_rules_appengine/appengine/py_appengine.bzl:211:48: Traceback (most recent call
 last):
        File "/home/gauthier_hubert/.cache/bazel/_bazel_gauthier_hubert/5b1014468b822716d4cb420dac37de95/external/io_bazel_rules_appengine/appengine/py_appengine.bzl", line 205
                rule(_py_appengine_binary_base_impl, at..."]))}, <2 more arguments>)
        File "/home/gauthier_hubert/.cache/bazel/_bazel_gauthier_hubert/5b1014468b822716d4cb420dac37de95/external/io_bazel_rules_appengine/appengine/py_appengine.bzl", line 211, in rule
                attr.label_list(allow_files = FileType([".yaml",..."]))
        File "/home/gauthier_hubert/.cache/bazel/_bazel_gauthier_hubert/5b1014468b822716d4cb420dac37de95/external/io_bazel_rules_appengine/appengine/py_appengine.bzl", line 211, in attr.label_list
                FileType([".yaml", ".py"])
FileType function is not available. You may use a list of strings instead. You can temporarily reenable the function by passing the flag --incompatible_disallow_filetype=false
ERROR: error loading package '': Extension file 'appengine/py_appengine.bzl' has errors
ERROR: error loading package '': Extension file 'appengine/py_appengine.bzl' has errors
INFO: Elapsed time: 3.404s
INFO: 0 processes.
`
### Steps to Reproduce
On debian 9
`
wget https://github.com/bazelbuild/bazel/releases/download/0.24.1/bazel_0.24.1-linux-x86_64.deb

echo b6fec7719046953f8b9b18bb798b8d11a84147b936c31e4cfe8d1e6184cc24ed  bazel_0.24.1-linux-x86_64.deb | sha256sum -c

sudo dpkg -i bazel_0.24.1-linux-x86_64.deb

rm bazel_0.24.1-linux-x86_64.deb

curl -sL https://deb.nodesource.com/setup_8.x | sudo -E bash -

sudo apt-get install nodejs

sudo apt install git

curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.34.0/install.sh | bash

source ~/.bashrc

nvm install 8.11.0

nvm ls

npm install -g @angular/cli

npm install --unsafe-perm node-sass

sudo apt install python-pip

# Create environment variable for correct distribution

export CLOUD_SDK_REPO="cloud-sdk-$(lsb_release -c -s)"

# Add the Cloud SDK distribution URI as a package source

echo "deb http://packages.cloud.google.com/apt $CLOUD_SDK_REPO main" | sudo tee -a /etc/apt/sources.list.d/google-cloud-sdk.list

# Import the Google Cloud Platform public key

curl https://packages.cloud.google.com/apt/doc/apt-key.gpg | sudo apt-key add -

# Update the package list and install the Cloud SDK

sudo apt-get update && sudo apt-get install google-cloud-sdk

pip install pycrypto

sudo apt-get update && sudo apt-get install google-cloud-sdk`

**Comment by gauthier1997** [comment]
Solved, just build the software with v0.24 of bazel and v8.11.0 of npm

**Comment by crendoth** [comment]
Hi @gauthier1997 
crendoth$ bash deploy.sh web prod
INFO: Checking for gcloud on PATH and version...
SUCCESS: gcloud was found on PATH and is at or above the minimum version.
INFO: Checking for bazel on PATH and version...
SUCCESS: bazel was found on PATH and is at or above the minimum version.
INFO: Checking for npm on PATH and version...
SUCCESS: npm was found on PATH and is at or above the minimum version.
INFO: Checking gcloud authentication...
INFO: Going to the loaner directory...
INFO: Initiating the build of the python deployment script...
ERROR: /private/var/tmp/_bazel_crendoth/46f551e05e204fec8f3bd9f21b8353d3/external/io_bazel_rules_appengine/appengine/py_appengine.bzl:211:48: Traceback (most recent call last):
	File "/private/var/tmp/_bazel_crendoth/46f551e05e204fec8f3bd9f21b8353d3/external/io_bazel_rules_appengine/appengine/py_appengine.bzl", line 205
		rule(_py_appengine_binary_base_impl, at..."]))}, <2 more arguments>)
	File "/private/var/tmp/_bazel_crendoth/46f551e05e204fec8f3bd9f21b8353d3/external/io_bazel_rules_appengine/appengine/py_appengine.bzl", line 211, in rule
		attr.label_list(allow_files = FileType([".yaml",..."]))
	File "/private/var/tmp/_bazel_crendoth/46f551e05e204fec8f3bd9f21b8353d3/external/io_bazel_rules_appengine/appengine/py_appengine.bzl", line 211, in attr.label_list
		FileType([".yaml", ".py"])
FileType function is not available. You may use a list of strings instead. You can temporarily reenable the function by passing the flag --incompatible_disallow_filetype=false
ERROR: error loading package '': Extension file 'appengine/py_appengine.bzl' has errors
ERROR: error loading package '': Extension file 'appengine/py_appengine.bzl' has errors
INFO: Elapsed time: 0.433s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (0 packages loaded)

I believe I am getting the exact same error as you were getting, however I was unable to resolve it by running it with v0.24 of Bazel and v8.11.0 of npm, any chance you have any idea how I can solve this now?

**Comment by helfrichmichael** [comment]
@crendoth can you confirm what version you are using from Github of the loaner project?

I believe `git log --pretty=format:'%h' -n 1` from the loaner directory should give you the last commit number. The latest commit we've made is: 1b61f5f.

We're working on making a new numbered release soon, but I don't have an ETA or timeline for that yet. It's possible that the 0.7.1a version is no longer working with the Bazel and dependency changes over the past couple of months.

Additionally, we recommend version 0.26.1 of Bazel per [this documentation](https://github.com/google/loaner/blob/master/docs/gngsetup_part2.md).

**Comment by crendoth** [comment]
@helfrichmichael Thanks for the reply
I have version 9f7e0b9
I currently also have version 0.24 of Bazel, so I will upgrade that to 0.26.1 and try getting the latest version of the project from GitHub

**Comment by helfrichmichael** [comment]
I'm going to close this given the age of your commit. I think updating Bazel to the recommended version and the latest commit should resolve this error for you.

**Comment by crendoth** [comment]
Hi @helfrichmichael how do I update to the latest commit number?

**Comment by helfrichmichael** [comment]
@crendoth https://github.com/google/loaner/commits/master should always provide you with the list of commits ranging from latest to oldest.

Hope that helps :)!
