### ISSUE TITLE
(Web app) Bazel build error - Python toolchain wanting v3

### ISSUE THREAD

**Issue by chrisnadonrbk** [google/loaner#68]
### Expected Behaviour
Web app builds and deploys successfully

### Actual Behaviour
Deployment fails with error about Python version

### Steps to Reproduce
1. Open terminal

2. CD to loaner root directory

3. Run:
cd loaner
bash deployments/deploy.sh web prod

4. Terminal read out:
[MacBook-Air:loaner Chris$ bash deployments/deploy.sh web prod --extra_toolchains=@rules_python//python:autodetecting_toolchain_nonstrict --v4
INFO: Checking for gcloud on PATH and version...
WARNING: Could not setup log file in /Users/Chris/.config/gcloud/logs, (IOError: [Errno 13] Permission denied: u'/Users/Chris/.config/gcloud/logs/2019.09.10/11.42.33.803816.log')
Updates are available for some Cloud SDK components.  To install them,
please run:
  $ gcloud components updateSUCCESS: gcloud was found on PATH and is at or above the minimum version.
INFO: Checking for bazel on PATH and version...
SUCCESS: bazel was found on PATH and is at or above the minimum version.
INFO: Checking for npm on PATH and version...
SUCCESS: npm was found on PATH and is at or above the minimum version.
INFO: Checking gcloud authentication...
WARNING: Could not setup log file in /Users/Chris/.config/gcloud/logs, (IOError: [Errno 13] Permission denied: u'/Users/Chris/.config/gcloud/logs/2019.09.10/11.42.35.762904.log')
INFO: Going to the loaner directory...
INFO: Initiating the build of the python deployment script...
INFO: Analyzed target //loaner/deployments:deploy_impl (0 packages loaded, 0 targets configured).
INFO: Found 1 target...
Target //loaner/deployments:deploy_impl up-to-date:
  bazel-bin/loaner/deployments/deploy_impl
INFO: Elapsed time: 0.350s, Critical Path: 0.02s
INFO: 0 processes.
INFO: Build completed successfully, 1 total action
Error occurred while attempting to use the default Python toolchain (@rules_python//python:autodetecting_toolchain).
According to '/Library/Frameworks/Python.framework/Versions/2.7/bin/python -V', version is 'Python 2.7.13', but we need version 3. PATH is:

/Users/Chris/Desktop/Work/GnG/google-cloud-sdk/bin:/Library/Frameworks/Python.framework/Versions/2.7/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Users/Chris/bin

Please ensure an interpreter with version 3 is available on this platform as 'python3' or 'python', or else register an appropriate Python toolchain as per the documentation for py_runtime_pair (https://github.com/bazelbuild/rules_python/blob/master/docs/python.md#py_runtime_pair).

Note that prior to Bazel 0.27, there was no check to ensure that the interpreter's version matched the version declared by the target (#4815). If your build worked prior to Bazel 0.27, and you're sure your targets do not require Python 3, you can opt out of this version check by using the non-strict autodetecting toolchain instead of the standard autodetecting toolchain. This can be done by passing the flag `--extra_toolchains=@rules_python//python:autodetecting_toolchain_nonstrict` on the command line or adding it to your bazelrc.

## Additional info

OS: MacOS
Loaner branch used: Master
Bazel version: 0.29.0 

Was previously on Bazel 0.22.0 and using Loaner branch 0.7.1, but having issues so started again with Master branch and this said it needed a minimum of Bazel 0.28.0 so updated to latest. 

Have no prior knowledge of using git/bazel/python etc so new to all this, be gentle :).

**Comment by kid-yume** [comment]
You are fine. What I do recommend, however is to downgrade your bazel to potentially 0.19 to avoid having to manipulate build files and have a clean install. Then you can always update it again once you have deployed. 


Uninstall the version you have:
sudo apt-get remove bazel

Installing Bazel
sudo apt-get install -y --no-install-recommends \
bash-completion \
g++ \
zlib1g-dev \
&& curl -LO "https://github.com/bazelbuild/bazel/releases/download/0.19.0/bazel_0.19.0-linux-x86_64.deb"

Then Run the installation:
sudo dpkg -i bazel_*.deb

Check your version
bazel version

You can now even go into the web app folder and check the build processes with
bazel build runfiles --incompatible_disallow_filetype=false

**Comment by chrisnadonrbk** [comment]
Thanks for the suggestion, unfortunately if I downgrade Bazel (was initially trying on Bazel 24.0) I get this error when building: 

ERROR: The bazel version installed is lower than the minimum required version (0.28.0), please update bazel.

This is running on the 'master' branch of the loaner files. Should I revert back to the 0.7.1 and start fresh with bazel 18 on there?

**Comment by kid-yume** [comment]
I would recommend that. The master branch is not recommended for use. 0.7.1 is a stable and the version I would suggest starting with.

**Comment by chrisnadonrbk** [comment]
Going back to 0.7.1 let me build correctly, thanks!
