### ISSUE TITLE
401 "get_user_email failed: No user account detected." when making API request

### ISSUE THREAD

**Issue by ampkeegan** [google/loaner#70]
Hello,

I've deployed a simple app script solution to move locked devices in to a specific OU in G Suite. When I initially deployed this, I received this error:

`"error": {
  "code": 401, 
  "errors": [
   {
    "domain": "global", 
    "message": "get_user_email failed: No user account detected.", 
    "reason": "required"
   }
  ], 
  "message": "get_user_email failed: No user account detected."
 }
}`

The problem went away one day without any changes on my part. The script worked fine for about 15 days, and now the same error is back. 

I've confirmed that I am running the script as the main GNG admin. I've logged in to the admin console and cloud.google.com correctly, and I can access the GNG admin portal. I can make the same request manually using the API explorer (https://apis-explorer.appspot.com).

Aside from waiting and hoping the problem goes away again, I was wondering if there is a solution or workaround I can implement now?

Thanks!

**Comment by kid-yume** [comment]
So here is kind of whats happening. In the process technically when you are doing a sign into Google when your opening the app via the web browser. You are giving the API your credentials and permission to access your account information. When you skip the process of Granting permission. That is why you are seeing this error. If you created a replicate endpoint without the "get_user_email" call you would stop getting that error.

**Comment by helfrichmichael** [comment]
We haven't heard back from your or others on this issue in a while so I'm going to resolve. Let us know if you're still having issues.
