### ISSUE TITLE
ERROR: get_user_email failed: No user account detected after initial Bootstrapping

### ISSUE THREAD

**Issue by joefollmann** [google/loaner#73]
I am working on building the Grab N Go app into my school district's loaner system, and working through the steps, I have reached the end of Step 2 and have built the app. I am receiving the error in the bottom of the screen, below the "Login" button, when going to opening the AppSpot page.

`ERROR: get_user_email failed: No user account detected.`

I have verified that group permissions are accurate and verified that my client-secret.json file is fresh. I am rather new to this process, and have been working through the process of building this with an outside company, so any additional information I can provide, please let me know. Thank you everyone.

Edit 9/24: Also, while trying to figure out the error, I determined that I did not see the step anywhere in the previous step about the `technical-admins` group. I created a superuser group, but wanted to make sure I have the right permissions.

**Comment by kid-yume** [comment]
It was a group that should have been made to dictate  the apps "Admins"  and the users that will be able to Bootstrap. `Superadmin_Group` is the `technical-admins` you could have named it something else. However its a group that should be created and have at least one member with that Super Admin Role you created.

**Comment by joefollmann** [comment]
> It was a group that should have been made to dictate the apps "Admins" and the users that will be able to Bootstrap. `Superadmin_Group` is the `technical-admins` you could have named it something else. However its a group that should be created and have at least one member with that Super Admin Role you created.

Thanks for your reply. I did have the Super admin group permissions set up with the service account, as well as Google Admin API settings. Are there any logs I can provide to help figure out where the error might be coming from? Thanks.

**Comment by kid-yume** [comment]
The error is coming from the backend taking in the user that authenticated against it during the log in process. Is your script a timed script or does it only run when there is a locked device?

**Comment by joefollmann** [comment]
Sorry, I was probably unclear in my original description. The issue is on the backend, when going to the page [app name].appspot.com. This is the screen that I am met with
![image](https://user-images.githubusercontent.com/55758975/65604488-31b6be80-df6d-11e9-9d49-d525bf0847be.png)

In the steps, I am at [this part](https://github.com/google/loaner/blob/master/docs/gngsetup_part2.md#bootstrapping). As you can see in the URL, it looks like it's trying to do the bootstrapping step. Thanks!

**Comment by kid-yume** [comment]
Ok, yes i was a bit confused. I do apologize. So, lets backstep a moment. Did you manually put that bootstrap url in or id it redirect you to the bootstrap page?

**Comment by joefollmann** [comment]
Not a problem, thanks so much for looking into this.

The URL comes from the App Engine>Versions. When I select the link, it redirects to that site with the "bootstrap" part in the URL.

**Comment by kid-yume** [comment]
awesome. So this is not something you are forcing. Now back to your Constants file. You filled in your Domains, and other variables you were suppose to fill in correct? and you downloaded the Alpha version of the app and now the master branch correct?

**Comment by kid-yume** [comment]
I would also check your config.ts file as well to verify that all variables are configured properly. You successfully uploaded the app. However, it seems there is an issue with a variable somewhere.

**Comment by helfrichmichael** [comment]
We haven't heard back from your or others on this issue in a while so I'm going to resolve. Let us know if you're still having issues.
