### ISSUE TITLE
npm ERR! Argument of type '{ static: boolean; }' 

### ISSUE THREAD

**Issue by ghost** [google/loaner#75]
### Expected Behaviour

Run loaner/loaner/deployments/deploy.sh
with successful deployment.

### Actual Behaviour

**COMMAND**: bash deployments/deploy.sh web prod
**OUTPUT**:

INFO: Checking for gcloud on PATH and version...
Updates are available for some Cloud SDK components.  To install them,
please run:
  $ gcloud components updateSUCCESS: gcloud was found on PATH and is at or above the minimum version.
INFO: Checking for bazel on PATH and version...
SUCCESS: bazel was found on PATH and is at or above the minimum version.
INFO: Checking for npm on PATH and version...
SUCCESS: npm was found on PATH and is at or above the minimum version.
INFO: Checking gcloud authentication...
INFO: Initiating the build of the python deployment script...
INFO: Analyzed target //loaner/loaner/deployments:deploy_impl (0 packages loaded, 0 targets configured).
INFO: Found 1 target...
Target //loaner/loaner/deployments:deploy_impl up-to-date:
  bazel-bin/loaner/loaner/deployments/deploy_impl
INFO: Elapsed time: 0.183s, Critical Path: 0.01s
INFO: 0 processes.
INFO: Build completed successfully, 1 total action
npm WARN ajv-keywords@3.4.1 requires a peer of ajv@^6.9.1 but none is installed. You must install peer dependencies yourself.
npm WARN webpack-dev-server@3.1.10 requires a peer of webpack@^4.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN webpack-dev-middleware@3.4.0 requires a peer of webpack@^4.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN gng@0.0.1 No description
npm WARN gng@0.0.1 No repository field.
npm WARN gng@0.0.1 license should be a valid SPDX license expression

audited 34199 packages in 7.01s
found 9 vulnerabilities (3 low, 3 moderate, 3 high)
  run `npm audit fix` to fix them, or `npm audit` for details

> gng@0.0.1 build:frontend /Users/trevorgevers/code/dito/grab-and-go/loaner/loaner
> webpack --config web_app/frontend/config/webpack.aot.js

Hash: aa009c7d190c611bba85
Version: webpack 3.11.0
Time: 13714ms
 1 asset
   [0] ./web_app/frontend/src/main.aot.ts 0 bytes {0} [built]

**ERROR in chrome_app/src/app/shared/chrome_app_platform_location.ts(45,15): error TS2304: Cannot find name 'unknown'.**
chrome_app/src/app/manage/shared/bottom_nav/bottom_nav_test.ts(66,35): error TS2345: Argument of type '{ static: boolean; }' is not assignable to parameter of type '{ read?: any; }'.
  Object literal may only specify known properties, and 'static' does not exist in type '{ read?: any; }'.
chrome_app/src/app/manage/status/status_test.ts(110,47): error TS2304: Cannot find name 'AnyDuringJasmineTypesMigration'.
chrome_app/src/app/manage/status/status_test.ts(113,49): error TS2304: Cannot find name 'AnyDuringJasmineTypesMigration'.
chrome_app/src/app/manage/status/status_test.ts(115,49): error TS2304: Cannot find name 'AnyDuringJasmineTypesMigration'.
chrome_app/src/app/manage/status/status_test.ts(118,49): error TS2304: Cannot find name 'AnyDuringJasmineTypesMigration'.
chrome_app/src/app/manage/status/status_test.ts(121,47): error TS2304: Cannot find name 'AnyDuringJasmineTypesMigration'.
shared/components/return_instructions/return_instructions.ts(34,34): error TS2345: Argument of type '{ static: boolean; }' is not assignable to parameter of type '{ read?: any; }'.
  Object literal may only specify known properties, and 'static' does not exist in type '{ read?: any; }'.
chrome_app/src/app/offboarding/app.ts(88,35): error TS2345: Argument of type '{ static: boolean; }' is not assignable to parameter of type '{ read?: any; }'.
  Object literal may only specify known properties, and 'static' does not exist in type '{ read?: any; }'.
chrome_app/src/app/offboarding/app.ts(90,42): error TS2345: Argument of type '{ static: boolean; }' is not assignable to parameter of type '{ read?: any; }'.
  Object literal may only specify known properties, and 'static' does not exist in type '{ read?: any; }'.
chrome_app/src/app/offboarding/app.ts(99,32): error TS2345: Argument of type '{ static: boolean; }' is not assignable to parameter of type '{ read?: any; }'.
  Object literal may only specify known properties, and 'static' does not exist in type '{ read?: any; }'.
chrome_app/src/app/offboarding/app.ts(100,41): error TS2345: Argument of type '{ static: boolean; }' is not assignable to parameter of type '{ read?: any; }'.
  Object literal may only specify known properties, and 'static' does not exist in type '{ read?: any; }'.
chrome_app/src/app/offboarding/app.ts(104,28): error TS2345: Argument of type '{ static: boolean; }' is not assignable to parameter of type '{ read?: any; }'.
  Object literal may only specify known properties, and 'static' does not exist in type '{ read?: any; }'.
chrome_app/src/app/onboarding/welcome/welcome.ts(29,35): error TS2345: Argument of type '{ static: boolean; }' is not assignable to parameter of type '{ read?: any; }'.
  Object literal may only specify known properties, and 'static' does not exist in type '{ read?: any; }'.
chrome_app/src/app/onboarding/app.ts(87,35): error TS2345: Argument of type '{ static: boolean; }' is not assignable to parameter of type '{ read?: any; }'.
  Object literal may only specify known properties, and 'static' does not exist in type '{ read?: any; }'.
chrome_app/src/app/onboarding/app.ts(89,42): error TS2345: Argument of type '{ static: boolean; }' is not assignable to parameter of type '{ read?: any; }'.
  Object literal may only specify known properties, and 'static' does not exist in type '{ read?: any; }'.
chrome_app/src/app/onboarding/app.ts(96,33): error TS2345: Argument of type '{ static: boolean; }' is not assignable to parameter of type '{ read?: any; }'.
  Object literal may only specify known properties, and 'static' does not exist in type '{ read?: any; }'.
chrome_app/src/app/onboarding/app.ts(98,32): error TS2345: Argument of type '{ static: boolean; }' is not assignable to parameter of type '{ read?: any; }'.
  Object literal may only specify known properties, and 'static' does not exist in type '{ read?: any; }'.
chrome_app/src/app/onboarding/app.ts(99,32): error TS2345: Argument of type '{ static: boolean; }' is not assignable to parameter of type '{ read?: any; }'.
  Object literal may only specify known properties, and 'static' does not exist in type '{ read?: any; }'.
chrome_app/src/app/onboarding/app.ts(100,41): error TS2345: Argument of type '{ static: boolean; }' is not assignable to parameter of type '{ read?: any; }'.
  Object literal may only specify known properties, and 'static' does not exist in type '{ read?: any; }'.
chrome_app/src/app/onboarding/app.ts(104,28): error TS2345: Argument of type '{ static: boolean; }' is not assignable to parameter of type '{ read?: any; }'.
  Object literal may only specify known properties, and 'static' does not exist in type '{ read?: any; }'.
chrome_app/src/app/onboarding/return/return_test.ts(101,47): error TS2304: Cannot find name 'AnyDuringJasmineTypesMigration'.
web_app/frontend/src/components/search_box/search_box.ts(67,28): error TS2345: Argument of type '{ static: boolean; }' is not assignable to parameter of type '{ read?: any; }'.
  Object literal may only specify known properties, and 'static' does not exist in type '{ read?: any; }'.
web_app/frontend/src/components/search_box/search_box.ts(68,39): error TS2345: Argument of type '{ static: boolean; }' is not assignable to parameter of type '{ read?: any; }'.
  Object literal may only specify known properties, and 'static' does not exist in type '{ read?: any; }'.
web_app/frontend/src/components/shelf_actions/shelf_actions.ts(43,35): error TS2345: Argument of type '{ static: boolean; }' is not assignable to parameter of type '{ read?: any; }'.
  Object literal may only specify known properties, and 'static' does not exist in type '{ read?: any; }'.
web_app/frontend/src/views/shelf_actions_view/shelf_actions_view.ts(35,30): error TS2345: Argument of type '{ static: boolean; }' is not assignable to parameter of type '{ read?: any; }'.
  Object literal may only specify known properties, and 'static' does not exist in type '{ read?: any; }'.
web_app/frontend/src/views/device_actions_view/device_actions_view.ts(41,39): error TS2345: Argument of type '{ static: boolean; }' is not assignable to parameter of type '{ read?: any; }'.
  Object literal may only specify known properties, and 'static' does not exist in type '{ read?: any; }'.
web_app/frontend/src/components/device_action_box/device_action_box.ts(73,33): error TS2345: Argument of type '{ static: boolean; }' is not assignable to parameter of type '{ read?: any; }'.
  Object literal may only specify known properties, and 'static' does not exist in type '{ read?: any; }'.
web_app/frontend/src/components/device_action_box/device_action_box.ts(74,31): error TS2345: Argument of type '{ static: boolean; }' is not assignable to parameter of type '{ read?: any; }'.
  Object literal may only specify known properties, and 'static' does not exist in type '{ read?: any; }'.
web_app/frontend/src/components/device_action_box/device_action_box.ts(75,27): error TS2345: Argument of type '{ static: boolean; }' is not assignable to parameter of type '{ read?: any; }'.
  Object literal may only specify known properties, and 'static' does not exist in type '{ read?: any; }'.
web_app/frontend/src/components/device_action_box/device_action_box.ts(76,29): error TS2345: Argument of type '{ static: boolean; }' is not assignable to parameter of type '{ read?: any; }'.
  Object literal may only specify known properties, and 'static' does not exist in type '{ read?: any; }'.
web_app/frontend/src/components/device_list_table/device_list_table.ts(62,24): error TS2345: Argument of type '{ static: boolean; }' is not assignable to parameter of type '{ read?: any; }'.
  Object literal may only specify known properties, and 'static' does not exist in type '{ read?: any; }'.
web_app/frontend/src/components/shelf_list_table/shelf_list_table.ts(53,24): error TS2345: Argument of type '{ static: boolean; }' is not assignable to parameter of type '{ read?: any; }'.
  Object literal may only specify known properties, and 'static' does not exist in type '{ read?: any; }'.

Child html-webpack-plugin for "index.html":
     1 asset
       [0] ./node_modules/html-webpack-plugin/lib/loader.js!./web_app/frontend/src/index.html 781 bytes {0} [built]
npm ERR! code ELIFECYCLE
npm ERR! errno 2
npm ERR! gng@0.0.1 build:frontend: `webpack --config web_app/frontend/config/webpack.aot.js`
npm ERR! Exit status 2
npm ERR! 
npm ERR! Failed at the gng@0.0.1 build:frontend script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/trevorgevers/.npm/_logs/2019-10-04T13_18_25_777Z-debug.log

### Steps to Reproduce

git clone https://github.com/google/loaner.git
follow instructions:
https://github.com/google/loaner/blob/master/docs/gngsetup_part2.md
bash deployments/deploy.sh web prod
have attempted to lock down package.json in order to use specified versions, deleted node_modules and reinstalled with same results.

**Comment by helfrichmichael** [comment]
I just finished fixing this internally :). It will be resolved in our next GitHub push along with upgrading Angular, Webpack, and all the other NPM dependencies...

If you would like to remediate this for yourself in the meantime, my suggestion would be to use Visual Studio Code and search the whole loaner repo for all instances of "AnyDuringJasmineTypesMigration".

Example: https://github.com/google/loaner/blob/master/loaner/chrome_app/src/app/manage/status/status_test.ts#L110

You can remove the `as AnyDuringJasmineTypesMigration` portion for each of the times you see these.

The other issues you're mostly hitting have to do with changes that were made to the ViewChild decorator in newer versions of Angular (8+ IIRC). So for that, check out the code and recommendation below.

Example: https://github.com/google/loaner/blob/master/loaner/shared/components/return_instructions/return_instructions.ts#L34

You can change:
`@ViewChild('returnAnimation', {static: false}) animationElement!: ElementRef;`
to
`@ViewChild('returnAnimation') animationElement!: ElementRef;`

You'll have to do this for each of the broken ViewChild decorators (it will tell you them when compiling). In the next release, we'll be sticking to the static param with us moving to the latest stable version of Angular.

There's a fair amount of tests that were fixed with upgrading Angular versions, so I'd say that even after you fix the above, you may still run into issues.

**Comment by tgevers** [comment]
Much appreciated, I had commented out the tests altogether, I too made the fix you suggested, removing {static: false}.
and am now getting another error on my mac.
I had to modify the following within the deploy.sh to get things to work:
![Screen Shot 2019-10-04 at 10 59 33 AM](https://user-images.githubusercontent.com/26672044/66222182-2c0c5780-e696-11e9-9ed6-ce8ebc3a16c5.png)
and I am getting the following output/error:
![Screen Shot 2019-10-04 at 11 00 59 AM](https://user-images.githubusercontent.com/26672044/66222237-4cd4ad00-e696-11e9-9c71-632716fc101b.png)

**Comment by tgevers** [comment]
I think I know why this is happening, and why I had to modify the script, appears as though there is an additional folder /loaner which ought not to be there, would you agree? really appreciate your assistance, thank you.
![Screen Shot 2019-10-04 at 11 18 49 AM](https://user-images.githubusercontent.com/26672044/66223322-ccfc1200-e698-11e9-838e-2e95a2cc1745.png)

**Comment by helfrichmichael** [comment]
Resolving this as this was fixed at HEAD in f6a3f28. 

Additionally, regarding the nested loaner folder, that is expected because of the project name being loaner on github (which means with git checkout that it will put it into a folder matching the project name). `loaner` is a folder within the repository.
