### ISSUE TITLE
py_appengine.bzl:211:48:  name 'FileType' is not defined

### ISSUE THREAD

**Issue by ashraftalib** [google/loaner#76]
I am running to build and deploy GnG Web app but I am getting issue in py_appengine.bzl 
name 'File Type' is not defined. Below is my terminal commands and result:

PS C:\GitHub\loaner\loaner> bash deployments/deploy.sh web prod
INFO: Checking for gcloud on PATH and version...
Updates are available for some Cloud SDK components.  To install them,
please run:
  $ gcloud components updateSUCCESS: gcloud was found on PATH and is at or above the minimum version.
INFO: Checking for bazel on PATH and version...
SUCCESS: bazel was found on PATH and is at or above the minimum version.
INFO: Checking for npm on PATH and version...
SUCCESS: npm was found on PATH and is at or above the minimum version.
INFO: Checking gcloud authentication...
INFO: Going to the loaner directory...
INFO: Initiating the build of the python deployment script...
ERROR: /root/.cache/bazel/_bazel_root/1f2ddb62dcbcd7f4a2e5e5a23f2dced6/external/io_bazel_rules_appengine/appengine/py_appengine.bzl:211:48: 
name 'FileType' is not defined
ERROR: error loading package '': Extension 'appengine/py_appengine.bzl' has errors
ERROR: error loading package '': Extension 'appengine/py_appengine.bzl' has errors
INFO: Elapsed time: 0.286s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (0 packages loaded)
PS C:\GitHub\loaner\loaner>

Please anyone help me why am I getting this issue ?

**Comment by mattford63** [comment]
We needed to downgrade our version of Bazel to one that still had the FileType definition - 0.19.2 I think worked for us.

**Comment by ashraftalib** [comment]
@mattford63 
I have installed Build label: 0.29.1. How can I downgared this ? or Uninstall it.

**Comment by David-Promevo** [comment]
I used:

rm -fr ~/.bazel ~/.bazelrc
rm -rf ~/.cache/bazel


David Aulick

Promevo | Customer Engineer

david.aulick@promevo.com | promevo.com

**Comment by helfrichmichael** [comment]
If you're on Debian/Ubuntu, it's pretty straightforward if you download the .deb package from the Bazel repository and then install it. It looks like you are on Windows, so you should just need to download and install this exe from Bazel.

https://github.com/bazelbuild/bazel/releases/download/0.23.0/bazel-0.23.0-windows-x86_64.exe
https://github.com/bazelbuild/bazel/releases/tag/0.23.0

**Comment by rcanu** [comment]
> We needed to downgrade our version of Bazel to one that still had the FileType definition - 0.19.2 I think worked for us.

This also worked for us. Although I had to uninstall the current version of bazel
