### ISSUE TITLE
Is there a way to make all survey responses required?

### ISSUE THREAD

**Issue by CoreyGriffin** [google/loaner#77]
### Expected Behaviour

Want all survey questions to be required

### Actual Behaviour
Users are leaving text fields blank

I see there is a boolean to set the survey as required https://github.com/google/loaner/blob/master/loaner/chrome_app/src/app/offboarding/app.ts#L204 but don't see where you actually set that

**Comment by helfrichmichael** [comment]
![image](https://user-images.githubusercontent.com/9116898/67211922-d23cb900-f41b-11e9-8a2c-bbb413290be7.png)

You can set this in the configuration view on the Web App in the Organization section. Hope that helps!

**Comment by CoreyGriffin** [comment]
@helfrichmichael Thanks Michael, totally missed that!
