### ISSUE TITLE
After returning device, in Web it is showing Return pending status. 

### ISSUE THREAD

**Issue by ashraftalib** [google/loaner#78]
### Expected Behaviour
When Device is returned, it should show that device is unassigned in Device list.  

### Actual Behaviour

It is showing assigned with Return pending in Status not unassigned. 

### Steps to Reproduce
First Login in Chromebook and Open Loaner app. Then use Grab and go app for that device.
And click return after few hours.

**Comment by helfrichmichael** [comment]
This is working as intended. A new user must login on the device to complete the return/assignment or you must audit the device to a shelf. Otherwise, the device will remain in a pending return state.

**Comment by helfrichmichael** [comment]
We haven't heard back from your or others on this issue in a while so I'm going to resolve. Let us know if you're still having issues.
