### ISSUE TITLE
Automatically returned on auditing of shelf for any device which is already assigned to a user and no notification is coming to admin after audit is done.

### ISSUE THREAD

**Issue by ashraftalib** [google/loaner#79]
### Expected Behaviour
On Auditing it should not return any device, which is already assigned to a user. And after audit, it should notify audit logs to admin as given in web apps's configuration of loaner.

### Actual Behaviour
On auditing of device in shelf for already assigned user, it is automatically returned.  No notification mail is coming for Admin to check audit logs.  
### Steps to Reproduce
From Chromebook user usage Loaner app for loaning a device. Now Admin will check and do some audit in Shelf for that device which is already assigned to a user.

**Comment by templesnr** [comment]
@ashraftalib - I think the logic is that when a shelf is audited the devices serial numbers are scanned and the web app marks them as being on that shelf.  If a user was logged-in to a loaner device then it is possible that they haven't gone through the return process before they put it on the shelf - or - the user may still have the device (so how have you got the serial number?) then the serial number is the key and the device is still audited as on the shelf.  I have done that if a user has called me and said the device was locked - then the device is unlocked and they have another few days of use if they need it.

**Comment by helfrichmichael** [comment]
If a device is audited, the device is unassigned and marked as available on a shelf. If the original user marks the device as returned, we treat it as pending return. The only way we unassign is if someone new logs in or the device is audited to a shelf.

I'm going to close, but if this doesn't answer that question, please let me know.
