### ISSUE TITLE
No option is to add Devices in Shelf

### ISSUE THREAD

**Issue by ashraftalib** [google/loaner#80]
### Expected Behaviour
I am adding a device in shelf for only audit case. There is no option add devices in Shelf. So that device can recognized easily in which shelf it is belonging.

### Actual Behaviour
Only one Device can be added for audit case. But there is no option to add many devices in Shelf. Is there any option to add devices or shelf is only for auditing purpose  ?

### Steps to Reproduce
Go to Web app of loaner and create a Shelf and click to this Shelf  then there is only Edit option. In Case Audit only one device can be added.

**Comment by DJNinNZ** [comment]
Hi there,
When I first set up the app I noticed this, as I also expected to be able to 'add' devices to a shelf. 
The only way I found to do this was through the process of auditing a shelf but I don't recall being limited to only auditing a single device.

**Comment by kid-yume** [comment]
The idea of the flow is that if a location had multiple shelves. Users could return the device to any shelf. Once the audit is done it shows where the device current location is. As you audit multiple devices it just appears in the list. You do not have to refresh or anything to audit more then one device.

**Comment by templesnr** [comment]
Yes @aaron - an important aspect is also that a device loses its
association with a shelf once it's on loan (as I understand).
We've already suggested a possible enhancement that a device can retain its
relationship with the shelf when on loan.
Temple

**Comment by ericwhiteau** [comment]
If you go with the transient nature of the use case.
Assume you have three different shelves in different areas of an office complex.
When I grab a Chrome book from shelf 1   on level one.  It is no longer associated with the shelf.
I use it all day, then return it to shelf 3  on the third floor, (as this was where I was working).
There is no real point in requiring the chromebook to go back to level one.  as this will all happen again the next day.....

Does that work for you?

**Comment by helfrichmichael** [comment]
We haven't heard back from your or others on this issue in a while so I'm going to resolve. Let us know if you're still having issues.
