### ISSUE TITLE
How is reporting done for the solution?

### ISSUE THREAD

**Issue by DJNinNZ** [google/loaner#81]
Hi there,
I noticed there was no built-in reporting in the admin console.

Do I need to build something in Google Sheets or Data Studio to pull data from Big Query?

Are there any sample templates?

Thanks

**Comment by templesnr** [comment]
Hi @DJNinNZ - [there's a thread in the Group](https://groups.google.com/d/topic/loaner/csnLi8L-tRM/discussion). I'm creating various reports, starting from queries in BigQuery and then rendering dashboards in Data Studio.  I'll share some more queries as they come, but some starters are in the thread.

**Comment by templesnr** [comment]
hey @DJNinNZ - I've pulled together various reports, including merging with other data that isn't from GnG, perhaps I can help?  Do you have any particular reports in mind?

**Comment by helfrichmichael** [comment]
It sounds like this was answered and there's some community contributions to this. I'm going to resolve/close. Let me know if you have any further questions.
