### ISSUE TITLE
Loaner App not popping up upon first login.

### ISSUE THREAD

**Issue by David-Promevo** [google/loaner#83]
### Expected Behaviour

Loaner App pops up on first login for a new user.

### Actual Behaviour

The onboarding process does not always appear when signing into a Chromebook for the first time. The loan is started and gets assigned to the user, but the application does not run on start and you can't get to the first sign in survey. If you click on the app in the tray, it'll bring you to the loan screen where you can extend or return the Chromebook. We just tested on a Chromebook as well and with five different sign ins, we could not get the initial survey to come up.  We tested with multiple users on different Chromebooks and the issue occurs intermittently. We have received survey responses from end users so it's definitely coming up for some employees.

Silent onboarding is off.

### Steps to Reproduce

Sign into Chromebook.

**Comment by helfrichmichael** [comment]
@David-Promevo can you confirm what version of the Chrome App you're running with regards to GitHub? You should be able to pull this info by running `git show` from the directory with your loaner Git repo. Additionally, does the organization have any proxy settings being forced by policy or extensions?

FWIW, the most recent push includes code that does verified onboardings (sends a request at the end of the onboarding to signify that an onboarding has finished). This will mitigate network flapping and proxy issues during the initial heartbeat we believe.

Relevant changes:
https://github.com/google/loaner/commit/372e475e06873b00ffee840d2a2500928287b7f2
https://github.com/google/loaner/commit/168cbffe13d30b9d963280272e3f7a0d41fa1893

In the next release, you'll see the following flip to False to turn on verified onboardings: https://github.com/google/loaner/blob/master/loaner/web_app/backend/models/device_model.py#L229

**Comment by githerbert** [comment]
Thanks for the response.


0.7.1a

Is that push at the master branch?  If so is there file(s) we can update to
add that functionality without breaking things :)

**Comment by helfrichmichael** [comment]
Yeah, the push I am mentioned is at master/HEAD. Once you've got all the Chrome Apps updated and all that (and everyone is getting the latest version), you can try flipping that boolean in the device_model.py file to False to basically enable verified onboardings. This means that the app will keep responding with start_assignment as true in the heartbeat until they've actually completed the onboarding.

When we have our next numbered release, I'll try to include some info on this in the release notes if possible.

**Comment by helfrichmichael** [comment]
We haven't heard back from your or others on this issue in a while so I'm going to resolve. Let us know if you're still having issues.
