### ISSUE TITLE
error in the bazel version

### ISSUE THREAD

**Issue by Roger-Soriano** [google/loaner#84]
###Expected Behaviour
error in the bazel version

### Actual Behaviour
Hello,
I'm following the steps to create a Grab and Go in Google appengine. I'm at step 6 Build and Deploy, in the command bash deployments/deploy.sh web prod. I get an error that bazel that is installed is lower than version 0.26.0.

r_soriano@cloudshell:~/python-docs-samples/appengine/standard/loaner/loaner$ bash deployments/deploy.sh web prod
INFO: Checking for gcloud on PATH and version...
SUCCESS: gcloud was found on PATH and is at or above the minimum version.
INFO: Checking for bazel on PATH and version...
Starting local Bazel server and connecting to it...
FATAL: Cannot get start time of process 0: (error: 2): No such file or directory
ERROR: The bazel version installed is lower than the minimum required version (0.26.0), please update bazel.
r_soriano@cloudshell:~/python-docs-samples/appengine/standard/loaner/loaner$

### Steps to Reproduce
Google App Engine Cloud Shell

**Comment by helfrichmichael** [comment]
Per the release notes and install instructions, currently we recommend using Bazel 0.26.* to deploy/build Grab and Go. There was a change in Bazel 0.27.0 where it defaulted various dependencies to newer versions of Python and this resulted in failed deployments.

https://github.com/bazelbuild/bazel/releases/tag/0.26.0 - Grab the release for your operating system here.

Let me know if you're still having issues after this.

**Comment by helfrichmichael** [comment]
We haven't heard back from you in a while, so I'm going to close out this issue. Let us know if you have any further issues.
