### ISSUE TITLE
Question: Does this work with multiple domains?

### ISSUE THREAD

**Issue by Nirchio** [google/loaner#86]
Hi, 

GnG can be used as centralized fleet managemnet with users in different domains? (i.e A coworking space)

Thanks

**Comment by helfrichmichael** [comment]
Grab and Go will only work for a singular G Suite organization currently. You can have multiple domains, but they MUST be a part of the same G Suite organization.

https://github.com/google/loaner/blob/master/docs/gngsetup_part2.md#step-5-customize-the-app-constants talks about setting up multiple domains.

**Comment by helfrichmichael** [comment]
We haven't heard anything further about this, so I'm going to resolve this issue.

**Comment by herandal17** [comment]
Hello, 

I refloat the thread. 

I currently have an external helpdesk team that needs access to GnG administration.
Being external they have a different domain to the main one, they are both within the same G Workspace console.

I have reviewed this section https://github.com/google/loaner/blob/master/docs/gngsetup_part2.md#step-5-customize-the-app-constants, changed the APP_DOMAIN variable and deployed the code again but I still can not access with the new domain, I get an error saying that "ERROR: test@ext.domain.net is not an authorized user for one of the domains: domain.net".

Does anyone know what can be happening? Is it possible to access with different domains?
Before making this change, the user did not directly log in to the administration by returning a FORBIDDEN message.

Thanks in advance.
