### ISSUE TITLE
Will not load devices

### ISSUE THREAD

**Issue by jimcollierGF** [google/loaner#87]
### Expected Behaviour
Device should load on the device screen

### Actual Behaviour
devices screen is blank and show an error.

### Steps to Reproduce

Click on devices and it show there are no devices load and we get the error below.  

![Screen Shot 2020-01-29 at 3 22 31 PM](https://user-images.githubusercontent.com/30299592/73394495-bca51e00-42ab-11ea-8cb1-774227f160da.png)

**Comment by helfrichmichael** [comment]
That doesn't look like an identifier for any Chrome device (serial number, asset, or chrome device ID). Can you provide some additional information about your deployment (what commit are you currently at, did this just start happening, can you view any devices, etc).

If you look at the network tab of the developer console in Google Chrome (https://developers.google.com/web/tools/chrome-devtools/network), can you see what requests appear to be failing?

**Comment by helfrichmichael** [comment]
We haven't heard back from you in a while, so I'm going to close out this issue. Let us know if you have any further issues.
