### ISSUE TITLE
Links in FAQ are not opening in Chrome

### ISSUE THREAD

**Issue by akshitbaunthy** [google/loaner#88]
### Expected Behaviour
Clicking on a link in FAQ should bring up that link in Chrome browser

### Actual Behaviour
Nothing happens when clicking on a link.

### Steps to Reproduce
In FAQs, add a link using markdown syntax or as text.
In case of markdown syntax, the link shows up anchored just fine but clicking on it does nothing.
In case of plain text, the link is anchored but again, clicking on it does nothing.

We have links in the troubleshoot page too (support.google.com) and that seems to work just fine. So I am assuming links in FAQ should work fine as well. However, the troubleshoot page is in Typescript (.ts) whereas the FAQs are in markdown format.
![Can open links that are in Troubleshoot tab (Typescript)](https://user-images.githubusercontent.com/50140727/73720464-fe204800-4747-11ea-839a-4d37cd28ef4e.png)
![Cannot open link that are in FAQ tab (markdown)](https://user-images.githubusercontent.com/50140727/73720472-024c6580-4748-11ea-8a7a-ca36ccea70c9.png)

**Comment by helfrichmichael** [comment]
Can you elaborate on what the ideal behavior would be (IE opening a new window with the referenced link)? If you inspect the anchor element, what does that URL look like in HTML (does it have a target attribute)?

**Comment by akshitbaunthy** [comment]
Sorry for the late response.
That's exactly it. I would expect clicking on the link to will cause it to open in a browser.
Not sure how I would inspect the anchor element of the chrome app.
If it helps, I used the following in MD - [via this link](https://docs.google.com/some-valid-link,"<some message>")

**Comment by akshitbaunthy** [comment]
I have pulled from the master branch and 0.7.1.

**Comment by helfrichmichael** [comment]
I reproduced just now. It looks like my suspicions were correct. It's not applying a target="_blank" attribute to the link which prevents Chrome Apps from opening the link to prevent malicious/unintended behavior.

JS Console Error: `Can't open same-window link to "https://www.google.com/"; try target="_blank".`

So I've just fixed this internally, but I don't know when we will make our next push. Given that, I'll give you the code you'll need to put in the FAQ component.

New code (to replace line 28-46):
```
export class FaqComponent implements OnInit {
  sanitizedFaqContent?: string|null;
  renderer = new marked.Renderer();

  constructor(
      private readonly http: HttpClient,
      private readonly sanitizer: DomSanitizer) {}

  ngOnInit() {
    this.renderer.link = (href, title, text) => {
      const html = this.renderer.link.call(this.renderer, href, title, text);
      return html.replace(/^<a /, '<a target="_blank" ');
    };

    this.getFaq().subscribe((response) => {
      this.sanitizedFaqContent = this.sanitizer.sanitize(
          SecurityContext.HTML, marked(response, {renderer: this.renderer}));
    });
  }
  /** Gets the FAQ from assets/faq.md file. */
  getFaq(): Observable<string> {
    return this.http.get('./assets/faq.md', {'responseType': 'text'});
  }
}
```
File: https://github.com/google/loaner/blob/master/loaner/chrome_app/src/app/manage/faq/faq.ts

**Comment by akshitbaunthy** [comment]
Trying it out right now.

**Comment by akshitbaunthy** [comment]
So that took a little longer than expected to show in the webstore. But it is fixed.
Thank you, @helfrichmichael. 😄
