### ISSUE TITLE
Loan duration time expired, can still login? Expected behviour?

### ISSUE THREAD

**Issue by mikepsada** [google/loaner#89]
We have noticed that once the loan duration time for a device is up, we are still able to log into the device and continue to work (it does not lock up right away). But after a few days after being overdue, the device is locked up and becomes unusable. We would like to understand this lockup behavior and how we can configure GnG to lock up the device right away or give a grace period allowing user to request more time before it locks up.

Thanks in advance

### Expected Behaviour
Loan duration expires, device not usable

### Actual Behaviour
Loan duration expires, can still use device for indeterminate amount of time

### Steps to Reproduce
Let loan duration expire, continue to use device

**Comment by templesnr** [comment]
hi @mikepsada - I just happened to see your post.  GnG is very relaxed about the loans, it does send reminders before the device is locked, but it ignores the duration that you set when you borrow it.  The device will only lock when the maximum loan duration (set in the configuration) is reached.

**Comment by mikepsada** [comment]
Thanks for the super quick response @templesnr !

I have a follow up question.

If I have the loan duration set to 3 days, and I want it to lock as soon as this time expires, I would set the max loan duration to 3 days as well (correct?). This would ensure the device would be locked at 3 days. (Or maybe set the max duration to 4 days, and they have a grace day)

BUT would the user be able to extend the loan, e.g. before the max of 3 days is up, extend it for another 3 days? Or since this is over the max it would not allow it? Thanks in advance!

-Mike

**Comment by akshitbaunthy** [comment]
@mikepsada - You can extend loan duration any number of times (in your case, 3) until the max loan duration date.
For example, 3 days from today is March 1. In your scenario, a user can extend his loan to a maximum date of March 1 only.
Simply put, a loan can be extended only till the following date - The day when loan was taken + Max loan duration.

**Comment by helfrichmichael** [comment]
Yep. All of the above is correct. You can make your default and max the same, though I can say internally we have the following model *currently*:

Default duration: 2 days
Max duration: 7 days

**Comment by winnie-lam** [comment]
Hi,

I'm having an issue with being locked out of the device.
We are testing loaner Chromebooks' lockout behavior. We followed the following steps to test it:
1) Set default loan duration to 1 day and max loan duration to 3 days and hit 'Save'
2) Sign into loaner Chromebook on March 6 (which means max loan duration ends on March 9)
3) Against expectations, successfully signed into loaner Chromebook on March 10. (Did not get the lockout screen)

Do you know why we're still not locked out of the chrome device?

Here is a screenshot:
![Screenshot_20200311-085732_Gmail](https://user-images.githubusercontent.com/22774435/76437494-e0fa1d00-6376-11ea-9d7d-902f797e3c43.jpg)

**Comment by templesnr** [comment]
Hi, the maximum loan duration is not an absolute.  If left long enough then
it will lock eventually, but it may not be on the exact day.  I don't know
the exact triggers in the code or how frequently the cycle of checks are.

**Comment by helfrichmichael** [comment]
@winnie-lam that sounds like a permission issue. Can you provide the actual "max_return_date" from Datastore for this device?

Additionally, do you see any errors in the logs (likely failed to execute a Directory API endpoint due to a permission scope issue)?

**Comment by winnie-lam** [comment]
Thanks for the replies!

@helfrichmichael do you mean "maximum_loan_duration" from the Datastore? I can't find "max_return_date" in the Datastore.

I'll check the logs. If it is a permission scope issue, how would I go about it to fix it?

**Comment by helfrichmichael** [comment]
Apologies, that's a computed date in the API response (`max_extend_date` is the field). On datastore for this device, does it report `true` in the `locked` field?

Depending on the error it may imply what the scope that's missing is. Feel free to provide it here and I can try to assist.

**Comment by winnie-lam** [comment]
I see that the "locked" field is set to "false". Would I need to set them all true? Is this a manual work I need to do all the time if I were to add a new device?

I don't have access to the log, but I will get back to you when I get access to it.

**Comment by helfrichmichael** [comment]
Nope, generally avoid making any edits in datastore (especially on devices and shelves due to indexing). That just indicates that it hasn't locked the device yet. If you open the web app (with the same account you're using on the Chromebook), open the developer tools and go to the network tab. Look for devices and view the Preview. I'm interested in what the `max_extend_date` field is reporting.

<img width="552" alt="Screen Shot 2020-03-11 at 8 10 38 PM" src="https://user-images.githubusercontent.com/9116898/76475246-a0c98780-63d4-11ea-8cbc-df8ea41ed8cd.png">

**Comment by winnie-lam** [comment]
Here is what you requested:
![image](https://user-images.githubusercontent.com/22774435/76549882-6a305300-644e-11ea-8bfe-27f351c3af4e.png)

**Comment by helfrichmichael** [comment]
Okay, interesting.  In Google Cloud Platform under Tools, there is a "Cloud Tasks" button. Once you visit that page, can you open the `process-action` task and see if it's paused or if there are any pending/failed tasks? The actual locking mechanism happens in: https://github.com/google/loaner/blob/master/loaner/web_app/backend/actions/lock_device.py

**Comment by winnie-lam** [comment]
@helfrichmichael - Thanks for the quick response! 

Here is what I see:
![image](https://user-images.githubusercontent.com/22774435/76562002-b0db7880-6461-11ea-8a9b-47cd36e8e76a.png)

**Comment by helfrichmichael** [comment]
Okay, so let's take a look at Datastore again and this time the `ReminderEvent` kind. Does yours match up with this one? Specifically the `name=3` entity in our list.

![image](https://user-images.githubusercontent.com/9116898/76566698-b0ec7000-6483-11ea-931f-e17390900fcd.png)
![image](https://user-images.githubusercontent.com/9116898/76566870-0f195300-6484-11ea-87ee-4489fb039296.png)

**Comment by winnie-lam** [comment]
@helfrichmichael - Sorry for the delay! Looks like everything matches up.

As you can see the max_extend_date is 2020-03-09 but 'locked' is still shown as 'false'. Someone borrowed a Chromebook on Feb 28, and it locked after 14 days on March 13. I borrowed a Chromebook on March 6, so I am expecting it to lock out on March 20, even though Max Loan Duration was set to 3 days at the time of borrowing a Chromebook. So it seems like 14 days is hardcoded in the app. Does the hardcoded 14 days override the set duration? Thanks!

**Comment by helfrichmichael** [comment]
Can you confirm what reminders it has sent thus far? Has it sent 3-4 reminders? Each matching the templates in the previous reply?

Looking at the code, I do not see this being hardcoded. It might be because of the gap in reminders however though.

**Comment by winnie-lam** [comment]
The first had a loan period of up to 14 days starting Feb 25, due Feb 28th.  The lockout finally kicked in on Mar 15th.  Then I set up a new loan, but this time the loan period is set to only 3 days.

The current loan (max 3 days) started on Mar 18 and due Mar 19th is still overdue.  It is currently not locked.  If this is hardcoded for 14 days, then I expect the lockout to happen around April 2nd.

![image](https://user-images.githubusercontent.com/22774435/77402998-c491b380-6d6c-11ea-94c1-e660d0877a05.png)

**Comment by helfrichmichael** [comment]
@winnie-lam and I are following up through internal channels on this matter (shoot me an email if you hit any further issues). I recommended moving to our latest version (master).

I'm going to resolve this issue given that this seems to be stemming from an old commit. Let me know if you have any further questions.
