### ISSUE TITLE
Readlink failure on Mac OSX

### ISSUE THREAD

**Issue by ampkeegan** [google/loaner#9]
### Expected Behaviour
$ bash deployments/deploy.sh web prod
INFO: Checking for gcloud on PATH and version...SUCCESS: gcloud was found on PATH and is at or above the minimum version.
INFO: Checking for bazel on PATH and version...
SUCCESS: bazel was found on PATH and is at or above the minimum version.
INFO: Checking for npm on PATH and version...
SUCCESS: npm was found on PATH and is at or above the minimum version.
INFO: Checking gcloud authentication...
INFO: Going to the loaner directory...
INFO: Initiating the build of the python deployment script...

### Actual Behaviour
INFO: Going to the loaner directory...
readlink: illegal option -- f
usage: readlink [-n] [file ...]
ERROR: The Bazel BUILD files appear to be missing.
### Steps to Reproduce
Follow deployment instructions on OSX, and run 'bash deployments/deploy.sh web prod' per instructions.

I was able to fix this by:

1. brew install coreutils
2. edit bash deployments/deploy.sh, change readlink to greadlink

**Comment by waltermeyer** [comment]
This is resolved on master.

https://github.com/google/loaner/commit/f48fe1cef13b80041db086330ba4af144311fcb1
