### ISSUE TITLE
Update Version

### ISSUE THREAD

**Issue by winnie-lam** [google/loaner#90]
Hi, 

If I were to redeploy the app from version 0.7.1 to master, can I just do a git clone of the master version, replace the config files, copy the loaner_chrome_app.zip to the new loaner folder and redeploy the web app? Or would I need to redeploy the chrome app too?

**Comment by cupajoe24** [comment]
You will need to update the Chrome app as well. Also please be careful when
updating as we cannot necessarily guarantee a bug free experience running
from head.

**Comment by winnie-lam** [comment]
Hi Joe, 

Thanks for getting back to me! I would just need to run this command "bash deployments/deploy.sh chrome prod" right? I wouldn't have to do step 1 thru step 7 from this documentation right? Just step 8.

**Comment by cupajoe24** [comment]
Yes I believe so

**Comment by winnie-lam** [comment]
Thank you!

**Comment by helfrichmichael** [comment]
I'm going to close this as it seems you've updated to the latest version. Feel free to reopen if this is not the case.
