### ISSUE TITLE
No variant found for unrecognized field: tags Error

### ISSUE THREAD

**Issue by winnie-lam** [google/loaner#91]
Hi @helfrichmichael, 

I upgraded to the master version of the code and now I'm receiving an error statement saying "No variant found for unrecognized field: tags" when trying to audit a device. How do I resolve this?

Thank you!

**Comment by helfrichmichael** [comment]
Can you grab any relevant errors from the [Chrome Developer Tools Console](https://developers.google.com/web/tools/chrome-devtools/open) and also from Google Cloud Platform logging? You should see an HTTP request with a bit more information about the error in GCP logging a few seconds after it fails to audit.

Additionally, have you ensured that every app engine service (action-system, chrome, default, and endpoints) are serving the latest version that you deployed?

My best guess right now is you don't have a datastore kind of "Tag", but that's a ballpark guess without any logs. If you're able to provide the HTTP request of the audit from the network tab of the Chrome Devtools as well, that might be useful too, but please blur/remove any sensitive information such as email, serial number, device id, etc.

**Comment by winnie-lam** [comment]
Hi Michael,

Thanks for the reply! Here are the logs you requested. I see a different
error message in the log now. I would get "AttributeError: 'NoneType'
object has no attribute 'sort'"

**Comment by winnie-lam** [comment]
Hi, 

I was wondering if this issue would be the cause of not being able to audit devices. I would get an internal server error when trying to audit a device. When I went into the logs to check what the bug was, I would see the error stated above. 

Please advise. Thank you!

**Comment by helfrichmichael** [comment]
Reviewing that error, it appears you might be missing some CoreEvents. In GCP, go to Datastore, and select the 'CoreEvent' kind from the dropdown.

Your events should match up to this:
<img width="747" alt="Screen Shot 2020-03-10 at 9 32 18 PM" src="https://user-images.githubusercontent.com/9116898/76373526-f93a4f80-6316-11ea-927a-f4290a6a26d9.png">

If they don't you can attempt to adjust or take a screenshot and we can poke at this further.

**Comment by winnie-lam** [comment]
@helfrichmichael - It looks like I was missing the device_audit. I just created the entity and it looks like it works now. Thank you so much for your help!

**Comment by helfrichmichael** [comment]
Awesome! I'm glad to hear that fixed it for you!
