### ISSUE TITLE
Health status images are "overflowing" in the web app

### ISSUE THREAD

**Issue by akshitbaunthy** [google/loaner#93]
### Expected Behaviour
Images depicting health status show up with correct size. Refer Chrome app for that.
![Chrome App - Normal](https://user-images.githubusercontent.com/50140727/75847897-8d338500-5e06-11ea-8842-3ccbb64e33bd.png)

### Actual Behaviour
Images depicting health status show up in huge size with img tags still visible
![Web App - Overflow](https://user-images.githubusercontent.com/50140727/75847362-f31f0d00-5e04-11ea-84e7-f0c549c6bef6.png)

### Steps to Reproduce
Follow steps to build web app

### Attempts to fix
I have tried changing `src` in lines 11, 22 and 33 of the file `loaner/loaner/shared/components/loan_management/loan_actions_card/loan_actions_card.ng.html` -
1. Putting png and or jpg images gives the following error while building -
```
ERROR in Module parse failed: Unexpected character '�' (1:0)
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
(Source code omitted for this binary file)
Child html-webpack-plugin for "index.html":
     1 asset
    Entrypoint undefined = index.html
    [0] ./node_modules/html-webpack-plugin/lib/loader.js!./web_app/frontend/src/index.html 781 bytes {0} [built]
npm ERR! code ELIFECYCLE
npm ERR! errno 2
npm ERR! gng@1.0.0 build:frontend: `webpack --config web_app/frontend/config/webpack.aot.js`
npm ERR! Exit status 2
npm ERR!
npm ERR! Failed at the g
ng@1.0.0 build:frontend script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/dotslash/.npm/_logs/2020-03-04T05_12_49_507Z-debug.log
```

2. Changing src to point to an image in Google Drive (which is shared publicly with link) gives a broken image.
![Web App - Drive URL](https://user-images.githubusercontent.com/50140727/75848185-704b8180-5e07-11ea-9b66-491b175cd6f9.png)

**Comment by helfrichmichael** [comment]
Can you confirm what commit you're using (using `git log`)?

My best guess right now is this is an issue with the SVG loader being used on the Web App (Chrome App uses a different SVG loader). If you're trying to use Google Drive for the image, it may cause some issues (due to pulling an image outside an approved URL and/or Google Drive's redirecting mechanism).

If you'd like to assist in the troubleshooting process, could you try changing your SVG loader in the web app and redeploying to see if that resolves the issue?

https://github.com/google/loaner/blob/master/loaner/web_app/frontend/config/webpack.aot.js#L32

Should change from
`{test: /\.svg$/, loader: 'svg-inline-loader'}`
To
```
{
  test: /\.svg$/,
  loader: 'file-loader?name=assets/[name].[hash].[ext]',
  options: {
    esModule: false,  // Prevents [object Module] output in IMG SRC.
  },
},
```

I haven't tested the above, so please do this in a development environment to make sure it doesn't break anything.

**Context**
[Chrome App SVG Loader](https://github.com/google/loaner/blob/master/loaner/chrome_app/config/webpack.common.js#L38)
[Web App SVG Loader](https://github.com/google/loaner/blob/master/loaner/web_app/frontend/config/webpack.aot.js#L32)

**Comment by akshitbaunthy** [comment]
Hello @helfrichmichael,

Thanks for the quick response. I'm not sure what commit you were looking for so I put all of them in  [this text file](https://github.com/google/loaner/files/4291036/git.commits.list.txt).

I'm building the app now with the changes to `webpack.aot.js` as you have suggested. The build process didn't throw any errors. I will get back to you soon.

**Comment by helfrichmichael** [comment]
Have you searched within Google Cloud Platform (specifically in the debug view of App Engine) to see if the referenced file (the SVG that it's looking for) is present anywhere? We're getting close to an answer I think.

**Comment by akshitbaunthy** [comment]
I'm back from my vacation.
Let me re-build the application on my test server by using the default config.
I'll get back here.

**Comment by akshitbaunthy** [comment]
So there indeed are the SVG files being referenced. But looks like they are in incorrect directories or incorrect directories are being referenced.
src in `loaner/loaner/shared/components/loan_management/loan_actions_card/loan_actions_card.ng.html` is `../../../assets/healthy.svg`
From my understading, that is `loaner/loaner/shared/assets/healthy.svg`. I could be wrong here since the web app is referencing the correct image but has the wrong size (with img tag still visible).
In debug view of the app engine, the location to healthy.svg is `:/loaner/web_app/"frontend/src"/"shared/assets"/healthy.svg`

**Comment by helfrichmichael** [comment]
@akshitbaunthy let me poke at this a bit more on my end and I'll try to see if I can resolve.

**Comment by helfrichmichael** [comment]
I found the problem(s). I'm working on a change internally now to remediate. Hopefully we can make a cut in the coming days or if it's a small enough change, I'll provide the relevant modifications in a follow-up response.

**Comment by helfrichmichael** [comment]
@akshitbaunthy here's the steps to fix until I get this changed submitted internally:

https://github.com/google/loaner/blob/master/loaner/web_app/frontend/config/webpack.aot.js#L32

Should change from
`{test: /\.svg$/, loader: 'svg-inline-loader'}`

TO

```
      {
        test: /\.svg$/,
        loader: 'file-loader',
        options: {
          name: '[name].[ext]',
          esModule: false,  // Prevents [object Module] output in IMG SRC.
          outputPath: 'shared/assets/',
        },
      },
```

Then in https://github.com/google/loaner/blob/master/loaner/web_app/app.yaml#L69

`static_dir: loaner/shared/assets/` Should change to: `static_dir: loaner/web_app/frontend/src/shared/assets/`

**Comment by helfrichmichael** [comment]
This is live in our latest push to master!
