### ISSUE TITLE
[Question] Build and deployment: Bazel error

### ISSUE THREAD

**Issue by WinsenTjhang** [google/loaner#94]
Hi,

I encountered this error at the deployment stage (**Alpha 0.7.1**)

![image](https://user-images.githubusercontent.com/43067876/77032906-e51ede00-69f9-11ea-9e6a-b6beb071eb0b.png)

I have tried to use bazel 0.26.0 and 0.26.1, I got the same error using both them.

Any idea where I might have got it wrong?

Thanks

**Comment by helfrichmichael** [comment]
AFAIK, Alpha 0.7.1 won't work because some of our Bazel WORKSPACE rules had changed. Can you try the master branch and see if you get the same results?

**Comment by WinsenTjhang** [comment]
I am trying the master branch this time and got this error

![image](https://user-images.githubusercontent.com/43067876/77489838-64def980-6e8d-11ea-8b74-3c34d4d924a1.png)

![image](https://user-images.githubusercontent.com/43067876/77489884-7fb16e00-6e8d-11ea-9458-d05e1dfd2c1c.png)

I'm using Bazel 0.26.1

**Comment by akshitbaunthy** [comment]
One of the issues is that you don't have or haven't properly installed the header files and static libraries for python dev.
sudo apt-get python{,3}-dev should do it (assuming you are running Debian).

**Comment by helfrichmichael** [comment]
Are you running on Google Compute Engine? Additionally, can you try running the following commands (assuming this is a Debian/Ubuntu distro).

`sudo apt-get install build-essential libssl-dev libffi-dev python-dev` we're still on PY2, so it's possible you're missing a few essential packages (if you're on a minimal distro of Linux, this will likely resolve your issue).

**Comment by WinsenTjhang** [comment]
Thanks, guys.

It worked after running `sudo apt-get install build-essential libssl-dev libffi-dev python-dev`

I am running on WSL (Windows subsystem), I think that's the reason for the error

**Comment by helfrichmichael** [comment]
Ah yeah, Windows provides a very minimal default installation as far as I can recall. Glad to hear it's working. I'll go ahead and close this out :).
