### ISSUE TITLE
Mass update to Devices

### ISSUE THREAD

**Issue by templesnr** [google/loaner#95]
A question I asked in the Groups but I didn't get an answer.  We need this because all our GnG ChromeBooks will be used by staff at home during this period where virtually all staff are working at home.  Is there a way to update the return date for all devices?  Obviously there's more than one way of allowing extended loans - does anyone have a view on this?

**Comment by helfrichmichael** [comment]
I think Joe followed up regarding this. I'll close. If you need further assistance, don't hesitate to let us know!
