### ISSUE TITLE
Web app internal server error, DirectoryRPCError: Forbidden, initial Bootstrapping

### ISSUE THREAD

**Issue by WinsenTjhang** [google/loaner#98]
Hi guys,

I got this error for my first web app access

![image](https://user-images.githubusercontent.com/43067876/78200211-a6008a80-74d9-11ea-8e4b-2d8ca94b8dfd.png)

![image](https://user-images.githubusercontent.com/43067876/78101630-d5f55280-7433-11ea-9645-d3bc69d1f33c.png)

Any idea where it got wrong?

Thank you

**Comment by helfrichmichael** [comment]
Hmmm you're getting a "accessNotConfigured" error which can mean various things all having to do with how you've granted access to APIs in Google Cloud Platform.

Here's some context:
https://cloud.google.com/resource-manager/docs/core_errors#FORBIDDEN
https://developers.google.com/console <- Double-check that you've enabled the APIs according to https://github.com/google/loaner/blob/master/docs/gngsetup_part1.md#step-2-set-up-an-app-engine-project-in-google-cloud (Specifically item 6 in that list).
https://console.developers.google.com/apis/api/admin.googleapis.com/overview (Admin SDK API)

**Comment by WinsenTjhang** [comment]
Found the problem, I didn't enable my admin SDK API. 

Thank you!

Proceeding: Accessing the web page and now got this error:
![image](https://user-images.githubusercontent.com/43067876/78206602-03510780-74eb-11ea-8260-50e3b16daba9.png)

The authorised URI looks good 
![image](https://user-images.githubusercontent.com/43067876/78206670-35fb0000-74eb-11ea-9b5e-48645186d7f6.png)

Does it have something to do with the different types of quotations of WEB_CLIENT_IDS?
![image](https://user-images.githubusercontent.com/43067876/78206813-8eca9880-74eb-11ea-9874-5e4ff3ee1884.png)

**Comment by helfrichmichael** [comment]
You need to whitelist the `https://` URL since you've only whitelisted the HTTP URL.

**Comment by WinsenTjhang** [comment]
It works now after rebuilding the apps with the zip file (taking suggestions from other cases). I did change the whitelist to https:// before rebuilding it from scratch, but still got the same error. 

Proceeding: Starting initial bootstrapping

![image](https://user-images.githubusercontent.com/43067876/78311567-f0970b00-759c-11ea-9b44-8a2345093586.png)

OU structure

![image](https://user-images.githubusercontent.com/43067876/78312178-af075f80-759e-11ea-89b0-f284ba8ac8a4.png)


Any idea what is the issue?

**Comment by helfrichmichael** [comment]
Any additional errors in the Google Cloud Platform logging view for this request?

Additionally, what does your ADMIN_EMAIL look like in [constants.py](https://github.com/google/loaner/blob/master/loaner/web_app/constants.py#L94)? I'm wondering if the email is formatted wrong. It should probably be your GSuite role account that you generated for this app.

Example of a properly formatted admin email: `ADMIN_EMAIL = 'test@test.com'`

**Comment by WinsenTjhang** [comment]
The admin email is formatted correctly. 

But anyway, I have got the app working now after deploying everything from scratch. 

I will continue testing the apps and features. Thanks!

**Comment by helfrichmichael** [comment]
Great to hear! I'll close this out since it's been resolved.
