### ISSUE TITLE
Multiple Domain, first bootstrap login error unauthorized

### ISSUE THREAD

**Issue by WinsenTjhang** [google/loaner#99]
### Expected Behavior
Succesful login and start bootstrapping

### Actual Behavior
![image](https://user-images.githubusercontent.com/43067876/78310262-16baac00-7599-11ea-9a71-3fa8e3aa8aa0.png)

### Steps to Reproduce
G Suite Primary domain = geekycloud.com
G Suite Secondary domain = digitallyinfinite.com

GCP domain = geekycloud.com
Parent OU = geekycloud.com

![image](https://user-images.githubusercontent.com/43067876/78310023-62208a80-7598-11ea-9cd2-85cc6651b3e8.png)

SUPERADMINS_GROUP = 'grabngo-admin@digitallyinfinite.com'

group member: winsen.loren@digitallyinfinite.com (superadmin)

web access with winsen.loren@digitallyinfinite.com

**Comment by WinsenTjhang** [comment]
The error seems to be solved by adding multiple domains in constant.py

![image](https://user-images.githubusercontent.com/43067876/78314363-7fa82100-75a5-11ea-9ee0-66c5f335e3ea.png)

And login with another admin account (winsen@geekycloud.com) is successful, but not with the second domain login.

But, my question is, is there any way to get other email accounts with the secondary domain to log in?

**Comment by helfrichmichael** [comment]
It should work assuming you have an array of domains (like in your second comment). What error are you hitting? The biggest requirement is they must be a part of the exact same GSuite account.

**Comment by WinsenTjhang** [comment]
They are part of the same GSuite account. 

Strangely, I am able to login with the secondary domain now after redeploying the apps. Thanks!

**Comment by helfrichmichael** [comment]
Great to hear. FWIW, it's possible you missed promoting a given version in App Engine or it cached/indexed an old value. I'll close this since you resolved. Thanks!
